### ISSUE TITLE
[Request] Support GOverlay 

### ISSUE THREAD

**Issue by VarLad** [bottlesdevs/Bottles#1087]
**Is your feature request related to a problem? Please describe.**
The DXVK HUD doesn't work a lot of times for some reason. The options are limited too and, it doesn't work with VKD3D games either (it used to, but now it doesn't) 

**Describe the solution you'd like**
[GOverlay](https://github.com/benjamimgois/goverlay) can be customized much better and more, but doesn't work with Bottles games for some reason. It would be nice if Bottles could somehow support GOverlay.

**Comment by mirkobrombin** [comment]
I'm a little overwhelmed by all these huds (which probably don't go because of flatpak or anything, I don't know, btw I’m able to use mangohud) and I think we need to figure out which one to implement rather than everyone (which really requires too much work if they have a lot of settings). For example, can GOverlay and Mangohud be compared? Can one replace the other?

**Comment by VarLad** [comment]
@mirkobrombin GOverlay uses MangoHUD, but has a lot of other features as well. 
It has easier GUI configuration, and has VkBasalt and Replay support as well. 

Unfortunately, I think the issue is GOverlay not supporting Flatpaks generally, so I guess this issue should be taken up with GOverlay

**Comment by VarLad** [comment]
On the other hand, I'd prefer to follow https://github.com/bottlesdevs/Bottles/issues/530 more closely :)
