### ISSUE TITLE
[Feature Request] delete runners and DLL components from preferences

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1211]
flatpak 2022.3.14-trento-3

it would be nice to have option to delete older and unused runners, DLL components from Preferences. Example a button to delete the component beside each components folder icon. User would click it to delete it from system. Currently the user needs to click the folder icon which opens their file explorer. then go up 1 level because it opens inside the component then manually delete it.

**Comment by Knebergish** [comment]
Additionally, because runners are removed manually by deleting directories, it's very easy to get a broken bottle.
For example, a user wants to update the runner to a new version. He downloads a new runner, deletes the old one, goes to the bottle to change its settings to a new runner, but... The "Components versions" section will not open due to an error:
`.../runners/somerunner/bin/wine64: No such file or directory`

I had such an error in another case - I installed the Flatpak version of Bottles and specified a custom path to existing bottles. Without installing the old version of the runner, I will not be able to change it to another (or manually changing configs).

I think it will be useful to be able to fallback to some standard runner if the currently used one does not exist in the system. Or at least show a warning in the UI and allow to change to an existing one.

**Comment by ghtesting2020** [comment]
I updated to latest version and I can now remove Runners and only DXVK-NVAPI from DLL Components. Is that intended?
What about:
DXVK
VKD3D
LatencyFleX
They do not have the 3 dots beside the folder icon to uninstall.

**Comment by mirkobrombin** [comment]
Because are in use
