### ISSUE TITLE
[Request]: Choose Wine Or Proton Version

### ISSUE THREAD

**Issue by trymeouteh** [bottlesdevs/Bottles#1249]
### Tell us the problem or your need

I am unable to choose a bottle to run with a specific version of Wine or a specific version of Proton. Please allow for the ability to create custom bottles were you choose the exact version of Wine or the exact version of Proton.

### Describe the solution you'd like

When creating a new bottle, you can choose to either select a Wine or Proton version in your computer (One you downloaded from another Wine manager such as PlayOnLinux) by choosing the wine executable in the directory

Or

You can choose a version of Wine or Proton and it will download that version and install it on the computer for you use to use for that bottle.

### Additional context and references

Also having settings to change the wine/proton version in the future in the bottle settings.

**Comment by mirkobrombin** [comment]
Creating the bottle:

- if you use gaming and application environments, Caffe will always be used because they have been tested with that

- if you use a custom environment you can select the runner you prefer

Once the bottle is created: You can change the runner in the bottle preferences, you can find it in the Components version section.

You can install other runners in software preferences.

Let me know if I misunderstood.

**Comment by trymeouteh** [comment]
PlayOnLinux allows you to download any version of Wine, including Wine v2.1 for example. I am requesting to add a feature for when you choose a runner to download older versions of Wine, Proton and even Proton-GE to download and install.

And to also have the ability to change the directory of a runner for a bottle. For example if I installed Wine 5.0.1 using PlayOnLinux, I can change the directory of the runner for a bottle to be the wine executable from Wine 5.0.1 from PlayOnLinux, for example, change the runner executable to... _/home/john/.PlayOnLinux/wine/linux-x86/5.0.1/bin/wine_

**Comment by mirkobrombin** [comment]
We have our repository for this purpose. Just open a new pull request there
