### ISSUE TITLE
[Bug]: New Bottles Is stuck at creating new Bottle and can't run installers or applications in the old one.

### ISSUE THREAD

**Issue by Octavion358** [bottlesdevs/Bottles#1296]
### Describe the bug

Bottles work but when I reboot or after 1 day the chaos begins. I have installed Ubuntu over and over again It still is a problem. When I reboot or wait 1 day my bottle is broken. When i try to create a new bottle It is stuck at windows settings something and i don't remember exactly what It is stuck at i only remember something with Windows. When i try to transfer my backup bottles folder to Bottles in the computer it's also problems.

### To Reproduce

![20220411_103022](https://user-images.githubusercontent.com/101971875/162696773-48c14ab1-88ed-40a3-b615-77b958ab347b.jpg)

### Package

Flatpak from Flathub

### Distribution

Ubuntu 20.04.4 LTS

### Health Check

Display 1920x1080

Graphics: nividia geforce gtx 1650

CPU: intel core i3 9100

8 GB Ram

256 GB SSD Toshiba MK327GSX

Gnome version 3.36.8

Operating system: Ubuntu 20.04.4 LTS 

Architectecture 64-BIT

Motherboard: lenovo 36EB

Computer: lenovo ideacentre T540-15ICB G gaming 

BIOS type: UEFI

BIOS version Lenovo O3QKT43A

### Display Backend used by Bottles

I don't know

### Additional context

When i try to transfer my backup bottles folder to Bottles in the computer it's also problems.

**Comment by Octavion358** [comment]
One more bug that i forgot to write when i should describe the bug. I can't run installers like Origin,
Battle.net or Ubisoft Connect or any other application or game in bottles after rebooting.

**Comment by mirkobrombin** [comment]
Please post the health check made by Bottles (menu -> health check). 

The only few times that a prefix broke "by itself" was because I had killed all the processes or because something in my environment caused a break (for example a WINEPREFIX env set by the system but this is now solved and Bottles does the override this, it might still be something like this). Can you run it from terminal (`flatpak run com.usebottles.bottles`) and post the output here of both Bottles startup and bottle creation?

And dont't forget the health check please.

**Comment by Octavion358** [comment]
You really are right i reinstalled the computer after   you said it was solved and i think if it was a bug you have fixed it. Also Bottles works now i have tested it and it never has worked for such a long time and it still works. I don't have run the application or game in terminal but it's not needed when it works.
