### ISSUE TITLE
[Bug]: 2022.5.14-trento-1 occasionally crashes when offline 

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1476]
### Describe the bug

Updated to 2022.5.14-trento-1 and bottles crashes immediately. I think it is due to being offline. I downgraded to  2022.5.14-trento  to be able to use normally again.

```
flatpak run com.usebottles.bottles

(bottles:3): Gtk-WARNING **: 21:28:02.233: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 21:28:02.234: Failed to load module "canberra-gtk-module"
21:28:06 (INFO) Catalog components loaded 
21:28:07 (INFO) Catalog installers loaded 
21:28:07 (INFO) Catalog dependencies loaded 
21:28:07 (INFO) Performing Bottles checks... 
21:28:07 (INFO) Dxvks found:
         - dxvk-1.10.1
 
21:28:07 (INFO) Vkd3ds found:
         - vkd3d-proton-2.6
 
21:28:07 (INFO) Nvapis found:
         - dxvk-nvapi-v0.5.4
 
21:28:07 (INFO) Latencyflexs found:
         - latencyflex-v0.1.0
 
21:28:07 (INFO) Runners found:
         - sys-wine-7.0
         - GE-Proton7-17
 
21:28:07 (WARNING) Connection status: offline … 
```

### To Reproduce

Update to latest
be offline
launch bottles

### Package

Flatpak from Flathub

### Distribution

Arch

### Health Check

```shell
Cannot get into bottles but no issues here in previous version
```

**Comment by mirkobrombin** [comment]
I'm not able to replicate also offline

**Comment by ghtesting2020** [comment]
This no longer happens. Restart probably helped and might have been due to arch linux updates waiting but cannot confirm.

**Comment by ghtesting2020** [comment]
It started happening again. it seems to not always happen. I don't know why. I didn't do any updates or restarts in between. It was working fine a couple hours ago, I close Bottles and try open again now and it crashes after a couple of seconds.

**Comment by ghtesting2020** [comment]
> After more testing (with multiple distro) I confirm that I'm not able to replicate in any way. It just works as expected. There are no edits which can cause crash on start or generally random crashes, only bug fixes to functions that need to manually activated, so I'll exclude a bug in Bottles itself, it's probably system related in somewhat

Thank you for trying again. It is very strange that 2022.5.14-trento does not crash when offline randomly but 2022.5.14-trento-1 does. I will just wait to update to a future version (like 2022.5.28) and hope it doesn't happen then. We  can leave this ticket open in case others have it happen as well in the meantime.

**Comment by jawadalkassim** [comment]
i'm having the same issue
fedora 36 kde
2022.5.14-trento-1


```
jawad@dell ~ [SIGKILL]> flatpak run com.usebottles.bottles
12:41:40 (INFO) Catalog components loaded
12:41:41 (INFO) Catalog installers loaded
12:41:43 (INFO) Catalog dependencies loaded
12:41:43 (INFO) Performing Bottles checks...
12:41:43 (INFO) Runners found:
	 - sys-wine-7.0

12:41:50 (INFO) Performing Bottles checks...
12:41:50 (WARNING) No dxvk found.
12:41:52 (INFO) Installing component: [dxvk-1.10.1].
12:41:52 (WARNING) File [dxvk-1.10.1.tar.gz] already exists in temp, skipping.
12:41:52 (ERROR) Downloaded file [dxvk-1.10.1.tar.gz] looks corrupted.
12:41:52 (ERROR) Source cksum: [08c0354ef2d2d22901545dcb153c618c] downloaded: [df873d15d9a38359d333b159009518ae]
12:41:52 (ERROR) Removing corrupted file [dxvk-1.10.1.tar.gz].
12:41:52 (ERROR) Extraction failed! Archive ends earlier than expected.
12:41:52 (WARNING) No dxvk found.
12:41:53 (INFO) Installing component: [dxvk-1.10.1].
Downloading dxvk-1.10.1.tar.gz: 100% [==================================================>

12:42:18 (INFO) Renaming [dxvk-1.10.1.tar.gz] to [dxvk-1.10.1.tar.gz].
12:42:18 (INFO) Dxvks found:
	 - dxvk-1.10.1

12:42:18 (INFO) Component installed: dxvk dxvk-1.10.1
12:42:18 (INFO) Component installed: dxvk dxvk-1.10.1
12:42:18 (WARNING) No vkd3d found.
12:42:20 (INFO) Installing component: [vkd3d-proton-2.6].
Downloading vkd3d-proton-2.6.tar.gz: 32% [================>   
jawad@dell ~ [SIGKILL]>
```

**Comment by jawadalkassim** [comment]
@mirkobrombin Do you mean internet speed test?

**Comment by mirkobrombin** [comment]
yes

**Comment by ghtesting2020** [comment]
> Can you both do a speed test and post the results here?
> 
> PS. still not able to replicate

I get 50 Mbps down, 10 Mbps up

**Comment by jawadalkassim** [comment]
![image](https://user-images.githubusercontent.com/48631694/169025110-1a9d451f-8c89-4045-83f8-89fe3d8a35d8.png)

**Comment by mirkobrombin** [comment]
So it's not a connection problem. I have tried with numerous distributions both in VM and container and on my installation, no problem. I believe it is something in your system somehow because (as mentioned) there are no changes in the latest release that affect start up or component installation.

**Comment by mirkobrombin** [comment]
Tested with Manjaro KDE too

**Comment by mirkobrombin** [comment]
There are only 18 commits from 2022.5.14 to 2022.5.14-1:

- https://github.com/bottlesdevs/Bottles/commit/ad08a2def61e19973bb58e0e0c83111182ad7c45
  Simply avoid raising an exception if the configuration is empty.
- https://github.com/bottlesdevs/Bottles/commit/8983510f5b1641d56f52fa113c22db02a959e35d
  Update code of conduct
- https://github.com/bottlesdevs/Bottles/commit/b8cd7fa9a52ac61ed668bc3351f7396642ddcc32
  Translations
- https://github.com/bottlesdevs/Bottles/commit/620a27c9c6b52dbfbc1bd2ea4154c8ba2ed9d100
  New `-b` option to launch Bottles with a pre-selected bottle, it's going to be ignored until you pass a bottle path name as argument (need user input)
- https://github.com/bottlesdevs/Bottles/commit/0a87e23dd4707d750c9f07f15dd6c9cca6753b6b
  Handle `TypeError` to avoid crash
- https://github.com/bottlesdevs/Bottles/commit/e66fe12224fdafcaba32db43b1fcf31bb13c6996
  New method to kill the wineserver (not used)
- https://github.com/bottlesdevs/Bottles/commit/4901008a34905b6d2d1c03cc4746757879b1d6f8
 Move to Result as return for the  `update_config` method and make the Wine sync change shutting down the wineserver (need user input)
- https://github.com/bottlesdevs/Bottles/commit/cf4c8ba321d24b6166c25b098e4d8046ef5ed66a
  lock some widgets before updating to prevent their callback
- https://github.com/bottlesdevs/Bottles/commit/d61400195ddb13ec5a26f4d6e2a266eb349ab75c and https://github.com/bottlesdevs/Bottles/commit/b771d99fa958c6993d7af92e00384226a29912d3
  UI changes
- https://github.com/bottlesdevs/Bottles/commit/29a4284601eee328fc868c9e7172f1954381a24b
  Make the bottle creation fails if the custom recipe is invalid, instead of fall-backing to the default one (need user input)
- https://github.com/bottlesdevs/Bottles/commit/d5d826a30093db50d68330687a40386b25a96c54
  Changing log style from `(date) LEVEL: message` to `date (LEVEL): message`
- https://github.com/bottlesdevs/Bottles/commit/c96dbea9bc98d82dc4ac5119b580d11457b8cd4f
  Log when the catalog is loaded and hide the no connection button by default
- https://github.com/bottlesdevs/Bottles/commit/1da713634e994c57d4cd49183d254644c69a2d9e
  Simply hide some widgets if using a Steam Proton prefix as bottle
- https://github.com/bottlesdevs/Bottles/commit/a5ba7ea3962686e02bf632362adf633c8ed7b51e
  Like before
- https://github.com/bottlesdevs/Bottles/commit/744db65f651516d9c198df147400fdcbfacc5b76
  Change release version


So I'm sure it's not caused by Bottles but it's system dependent in some way.

**Comment by ghtesting2020** [comment]
@mirkobrombin 
I found a new error in journalctl, does it mean anything to you? I tried 2022.5.14-trento-3 and it is also crashing. I downgraded again to 2022.5.14-trento-1 and no more crashing.
```
xdg-desktop-portal-kde[1902]: xdp-kde-settings: Namespace  "org.gnome.desktop.a11y.interface"  is not supported
audit[7426]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 pid=7426 comm="bottles" exe="/usr/bin/python3.9" sig=11 res=1
kernel: bottles[7426]: segfault at 47ae8a1a ip 000068729ce0e924 sp 000074123fcf2ba8 error 6 in libgtk-3.so.0.2404.29[68729cd45000+3f4000]
kernel: Code: 89 fb 48 83 e7 fc 83 e3 03 48 83 ec 08 e8 84 fb ff ff c1 e0 02 09 d8 48 8b 5d f8 c9 c3 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa <83> 2f 01 74 07 c3 66 0f 1f 44 00 00 55 48 89 e5 41 54 49 89 fc 48
kernel: audit: type=1701 audit(1653056370.054:113): auid=1000 uid=1000 gid=1000 ses=1 pid=7426 comm="bottles" exe="/usr/bin/python3.9" sig=11 res=1
kernel: audit: type=1334 audit(1653056370.061:114): prog-id=22 op=LOAD
kernel: audit: type=1334 audit(1653056370.061:115): prog-id=23 op=LOAD
kernel: audit: type=1334 audit(1653056370.061:116): prog-id=24 op=LOAD
kernel: audit: type=1130 audit(1653056370.061:117): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-7452-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=su>
audit: BPF prog-id=22 op=LOAD
audit: BPF prog-id=23 op=LOAD
audit: BPF prog-id=24 op=LOAD
audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-7452-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
systemd[1]: Started Process Core Dump (PID 7452/UID 0).
systemd-coredump[7453]: [🡕] Process 7426 (bottles) of user 1000 dumped core.
systemd[1]: systemd-coredump@1-7452-0.service: Deactivated successfully.
```

**Comment by mirkobrombin** [comment]
Is the bug reproducible with the `bottles` AUR package?
