### ISSUE TITLE
[Request]: add dgVoodoo2 support for increased compatibility and performance with old games

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#1572]
### Tell us the problem or your need

To increase compatibility and performance with very old games like the original Sims i have been read that dgVoodoo2 helps
https://github.com/dege-diosg/dgVoodoo2
the project is in archive state since the maintainer is busy but it is still very much up to date

### Describe the solution you'd like

add dgVoodoo2 support for increased compatibility and performance with old games

**Comment by mirkobrombin** [comment]
Archived mean deprecated. It is bad practice to implement deprecated technologies and tools because those will not receive updates. The last commit is January and it is quite recent but when a repository is marked as archived, it means that it will no longer receive commits, so in a few months that commit will be very old and will remain the last.

**Comment by ghtesting2020** [comment]
> Archived mean deprecated. It is bad practice to implement deprecated technologies and tools because those will not receive updates. The last commit is January and it is quite recent but when a repository is marked as archived, it means that it will no longer receive commits, so in a few months that commit will be very old and will remain the last.
> 
> It is preferable to let the user use it with some tweaks, such as launch options.

It is still having minor hotfixes added. If you look here https://github.com/dege-diosg/dgVoodoo2/releases the latest hotfix was April 10.

**Comment by mirkobrombin** [comment]
It's weird behavior to archive the repository and then release fixes. I also miss how to validate those binaries. How can I be sure of their legitimacy if the source is not public?

Re-opening for discussion.

**Comment by ghtesting2020** [comment]
> It's weird behavior to archive the repository and then release fixes. I also miss how to validate those binaries. How can I be sure of their legitimacy if the source is not public?
> 
> Re-opening for discussion.

Maybe  @dege-diosg could provide some input?

**Comment by dege-diosg** [comment]
I don't think dgVoodoo should be "integrated" into anything. It's a standalone software and not even for linux.

**Comment by mirkobrombin** [comment]
> I don't think dgVoodoo should be "integrated" into anything. It's a standalone software and not even for linux.

thanks for the explanation

**Comment by ghtesting2020** [comment]
> I don't think dgVoodoo should be "integrated" into anything. It's a standalone software and not even for linux.

I don’t think you fully understood what Bottles or Wine is and does. It’s for emulating Windows games/apps on Linux. It is definitely being used by others on Linux for compatibility. It’s just a wrapper afterall.

https://www.reddit.com/r/linux_gaming/comments/r4zpjz/using_dgvoodoo2_on_linux_to_run_pre_directx_9/

https://www.reddit.com/r/linux_gaming/comments/axzrsp/why_are_people_using_dgvoodoo2_and_dxvk_for_dx9/

**Comment by dege-diosg** [comment]
No, I very well know about that. But unlike the stuff you're referring to, dgVoodoo is not an open source library to fiddle with but a standalone software targeting Windows, albeit without an installer, but with its own configurator.
Typically not a thing that's meant to be integrated into any general framework/OS layer.

**Comment by soredake** [comment]
Lutris for example have it intergrated already https://github.com/lutris/lutris/pull/3824

**Comment by tannisroot** [comment]
We indeed do have dgvoodoo2 available as non-default option for DDRAW (Direct3D 2-7) games that don't work too well with WineD3D. There aren't too many of them but enough to warrant the option.
Additionally, there's a bonus functionality to this: since Dgvoodoo2 translates DDRAW to D3D11, which in turn is translated to Vulkan by DXVK, it allows to upscale these old games using AMD's Super Resolution. Those old games that only present at fixed, outdated resolutions like 800x600 or 1024x768 look really sharp and neat at any target resolution, even 4K.
While dgvoodoo2 is indeed closed source, I see no reason for the author to include malicious code in the software, seeing how the same 3d translation solution is used in many re-releases of old games.

**Comment by mirkobrombin** [comment]
The problem remains that the project appears abandoned. If the developer doesn't deny I can't offer it in Bottles. It might make sense to make a guide on how to proceed manually.

**Comment by dege-diosg** [comment]
> The problem remains that the project appears abandoned. If the developer doesn't deny I can't offer it in Bottles. It might make sense to make a guide on how to proceed manually.

I agree, that's the best solution.

**Comment by tannisroot** [comment]
Abandoned? Latest dgvoodoo2 version was released in April:
http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2/

As for a way to contact the developer, we at Lutris did it via the dgVoodoo2 section on Vogons, which appears to be fairly active.
https://www.vogons.org/viewforum.php?f=59

**Comment by tannisroot** [comment]
Here's the forum post I made before adding dgvoodoo2:
https://www.vogons.org/viewtopic.php?f=59&t=62212

**Comment by dege-diosg** [comment]
> Here's the forum post I made before adding dgvoodoo2: https://www.vogons.org/viewtopic.php?f=59&t=62212

Yes, I remember.

**Comment by mirkobrombin** [comment]
> Abandoned? Latest dgvoodoo2 version was released in April: http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2/
> 
> As for a way to contact the developer, we at Lutris did it via the dgVoodoo2 section on Vogons, which appears to be fairly active. https://www.vogons.org/viewforum.php?f=59

I don't question that, but I'm referring to the state of the repository and the intent of the developer. The repository is archived and mentions "I don't have time for this project so I put it into archived state for a while. There is no point to have new issue entries waiting for answers in vain."  which assumes it is (currently) abandoned and does not provide support. As Bottles, we cannot take the responsibility for receiving and dealing with issues regarding a project that we do not develop or maintain.

The project itself is great and I would be happy to provide it (as is) in Bottles allowing the user to use it in their own prefixes but I cannot do this due to its current / apparent state.

It can be assumed that we are not responsible for offering support and that we should limit ourselves to offering integration support (as we do for DXVK, VKD3D, LatencyFlex etc ...) but when we provide access to an "abandoned" project, we they are responsible for offering support to users in some way.

**Comment by boobthecat** [comment]
If it isn't going to be integrated can you guys at least make a guide on how to use it with Bottles? Kinda bummed because some games straight up wont work without this.

**Comment by boobthecat** [comment]
@mirkobrombin If it isn't going to be integrated can you guys at least make a guide on how to use it with Bottles? Kinda bummed because some games straight up wont work without this.

**Comment by orowith2os** [comment]
Any guide you follow for normal Wine will work with Bottles as well.
