### ISSUE TITLE
[Request]: Flatpak Permissions Warning

### ISSUE THREAD

**Issue by AlexandrosKap** [bottlesdevs/Bottles#1586]
### Tell us the problem or your need

If you try to run a program that isn't in a directory that Bottles has access to, then there is no indication that something went wrong.

### Describe the solution you'd like

Maybe display a message that tells you to change the Flatpak permissions.

**Comment by mirkobrombin** [comment]
Hi, I need info. How do you get to the file from Bottles if it don't have access to it?

Bottles uses portals to access files without permissions on demand.

**Comment by AlexandrosKap** [comment]
By default, when I click on the "Run executable" button, a file manager appears and I select a file inside the Documents directory.
After that nothing happens.

To solve this, I have to use a program called Flatseal and enable "All user files" for Bottles.
If I now try again to run an executable inside that directory, it just works.

I hope this helps.

**Comment by mirkobrombin** [comment]
Actually Bottles is using a portal to reach the file, the problem here is that file need more resources in the same folder. We are waiting for the neighbouring portal which will fix this https://github.com/flatpak/xdg-desktop-portal/issues/463

Tracking here https://github.com/bottlesdevs/Bottles/issues/413
