### ISSUE TITLE
[Request] dont expose /home

### ISSUE THREAD

**Issue by biji** [bottlesdevs/Bottles#184]
**Is your feature request related to a problem? Please describe.**

When running from flatpak, do not expose /home to protect from malwares

**Comment by mirkobrombin** [comment]
You can change bottles permissions with [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal)

**Comment by biji** [comment]
Thanks, tried to remove `xdg-*` using Flatseal
It would be good for new option `Sandbox mode` to not linking `My Documents`, etc.

**Comment by mirkobrombin** [comment]
It might be interesting but at the moment I want to focus on the main purpose of bottles and the development of v4, without adding too many other tasks.

**Comment by jannuary** [comment]
cc @LeandroStanger

**Comment by ManIVIctorious** [comment]
Since wine is often used to run production software instead of just games, this doesn't sound like a sane default configuration. If you would e.g. use bottles for microsoft office support, the applications would be rather useless without access to documents.

What could be done though, would be to make bubblewrap a dependency of the project and add a sandboxing gui, applicable to any environment/bottle. Unfortunately, I have no experience with bubblewrap inside a sandbox (although it should be possible since a little bit more than a year ago with recent flatpak versions), and therefore can't estimate how much work this would be.

**Comment by mirkobrombin** [comment]
Ref: https://github.com/bottlesdevs/libbottles/issues/1
