### ISSUE TITLE
[Bug]: Renaming a program creates a new entry instead of renaming the entry

### ISSUE THREAD

**Issue by CSalsa** [bottlesdevs/Bottles#1882]
### Describe the bug

Adding multiple programs with the same name under Programs and then attempting to at least one of them will create a copy of the program in the list of programs and make the first copy of the instance being renamed unable to be hidden or removed.

Before renaming:
- Launcher
- Launcher

After renaming one of them to Launcher 2:
-Launcher
-Launcher
-Launcher 2

I would rather it look like:
-Launcher
-Launcher 2

I expected the program being renamed to have the link with the original name removed or whatever happens behind the scenes. RENAMING IT DOES WORK if I close out of and reopen Bottles itself after step 2 under "To Reproduce" but I assume that it was not intentionally made so unintuitive.

### To Reproduce

1. Add one program named "X" through the + button
2. Add different program with the same name "X" the same way as in step 1.
3. Rename either one of the programs.

### Package

Flatpak from Flathub

### Distribution

SteamOS 3.2

### Troubleshooting Logs

```shell
Version: 2022.7.28-brescia-1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve15-1-neptune-02197-gf6ec7ad3762a
Distro:
    Name: GNOME
    Version: '"42 (Flatpak runtime)"'
Disk:
    Total: 7779737600
    Free: 7779594240
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 12.5GiB
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

**Comment by mirkobrombin** [comment]
I'm not sure I understood the problem well but I'll try to reproduce it

**Comment by TheEvilSkeleton** [comment]
They're saying that Bottles creates a new entry when renaming a bottle under the same name as another.

So, two bottles you created are called `X`. When you rename one of the bottles, it recreates a brand new entry instead of renaming the existing entry.

**Comment by siroccal** [comment]
I also ran into this bug. But you don't even have to add multiple programs. Just adding any executable/program causes a mess when you change any option for the added entry or rename it.

The problem is that when you add a program, the `key` in `External_Programs` (in `bottle.yml`) is set to the executable filename instead of to a UUID, and while `executable`, `name`, and `path` are added, the `id` is missing. If you then change any option or rename the entry, another `key` will be added with value `null`, which contains an `id` of value `null`.

If you add a program, directly close Bottles, and then start it again, it will convert the `key` in `External_Programs` from the filename to a UUID and it will also add an `id` set to the UUID. Then everything works fine and you can change options and rename the entry as intended.
But if you add a program, change some option or rename it, and then close Bottles and restart it again, you'll get an entry that's permanently stuck. That's because its `id` is not missing, but is set to `null`. And when Bottles starts, it converts the `key` to a UUID and adds an `id` if it's missing, but it doesn't set the `id` to a UUID if it's set to anything (including `null`). Also if the `key` is set to a UUID but the `id` is missing, then on startup an `id` gets added but set to a UUID different from `key`, which causes another stuck entry.

Workaround for now: after adding any program, don't rename it or change anything about it, and restart Bottles. After that, everything works fine.

Probable bug fix: when a program is added (via `btn_add` in `bottle_programs.py`), its `key` in `External_Programs` (in `bottle.yml`) should be directly set to a UUID (and not to its filename) and its `id` should be added and set to the UUID as well.
Suggestion: as any `key` must equal its `id` value, why not just get rid of the `id` altogether and always have the `key` be a UUID and refer to that? Or is that the plan already?
