### ISSUE TITLE
[Request]: Theming bottles

### ISSUE THREAD

**Issue by dr-nemesis-96** [bottlesdevs/Bottles#1918]
### Tell us the problem or your need

it seems you can actually theme wine to your liking, it will be just soo good to theme it anything but vanilla theme

check it out 
https://gist.github.com/Zeinok/ceaf6ff204792dde0ae31e0199d89398

### Describe the solution you'd like

add a menu to change theme, from bottles app

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting. 
I'm sorry but this feature will not be integrated into Bottles because it is too specific and not essential for the purpose of managing the prefix. Also changing the theme of apps could damage the software and we don’t want to bother the developers. Honestly this already happens with Wine as the themes used are not faithful replicas of Windows themes and I don't want to fuel the problem.
