### ISSUE TITLE
[Request]: Add League of Legends and Garena League of Legends Installers.

### ISSUE THREAD

**Issue by zihadio** [bottlesdevs/Bottles#1985]
### Tell us the problem or your need

Requesting a installer for Riot League of Legends and Garena League of Legends installer. 
Both work perfectly well in Lutris [Riot League of Legends](https://lutris.net/games/league-of-legends/), [Garena League of Legends](https://lutris.net/games/garena/).

Honestly that's the only thing I use lutris for nowadays. Bottles is far batter to play with.

### Describe the solution you'd like

Port the already stable League installer from Lutris to Bottles.

**Comment by mystrdat** [comment]
Any reason to close the issue? League installs but crashes after clicking the Play button on the current version of Bottles flatpak and it would be amazing to use this nice app for it instead of Lutris (I only use it for League). Not mentioning it doesn't work on flatpak before 1.15 (which is barely out at this time) and you need to follow a specific guide from /r/leagueoflinux to work around the installer issues anyway. Given League's popularity, having a simple working way of installing League on Linux might significantly boost this app's popularity. I would think it's a wide-open opportunity, please consider sensei @mirkobrombin 🙏🏻

I'd love to help but have near zero experience with Wine / Proton code. 😢
