### ISSUE TITLE
[Request]: Tell the user to install optional components through flatpak

### ISSUE THREAD

**Issue by Heus-Sueh** [bottlesdevs/Bottles#2008]
### Tell us the problem or your need

![Screenshot from 2022-08-31 15-20-47](https://user-images.githubusercontent.com/98482469/187753094-6a0b2299-38f4-4fe3-9f0f-3654708f2064.png)

### Describe the solution you'd like

tell the user to install MangoHud from flatpak to enable MangoHud as an option 

### Other solutions?

flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud

### Additional context and references

MangoHud was not available to enable even though I installed the rpm package, I only found out that this option is available by installing it with flatpak.

**Comment by Heus-Sueh** [comment]
the same thing should be done for gamescope, I just found out that this option is available by installing with flatpak.

**Comment by jannuary** [comment]
This makes sense to me - it's really unfrendly to quietly block features without any obvious way to use them

**Comment by TheEvilSkeleton** [comment]
Honestly, I would prefer including these extensions by default.

**Comment by jannuary** [comment]
These are very much optional and the package is bloated as is already.

**Comment by TheEvilSkeleton** [comment]
They're optional but I prefer having them installed by default so users don't have to manually install them. As someone who is proficient with Flatpak's CLI, it is NOT user friendly, and now that vkBasalt and MangoHud flatpaks have two different branches, GNOME Software is quite unclear about it.

**Comment by Pixelnarium** [comment]
Gamescope is not my package. I just send a PR for updating it so that it works with Steam.

**Comment by TheEvilSkeleton** [comment]
I opened https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/59.

**Comment by Pixelnarium** [comment]
No problem. As far as I know GNOME 43 is planned for release in 3 weeks. The current in-dev Gnome 43 flatpak runtime is based on 22.08. So when you move to this new runtime it will be working again for another year. But yeah. Long term there needs to be another solution.

**Comment by Noobao** [comment]
1+ for this,i had to search a fair bit to install vkbasalt and mangohud and have it working with the flatpak version since both of these are not on flathub,this would have solved my issue out of the box and i also doubt most people would mind it being about 25mb more heavy considering the functionality it brings.

However the issue with gamescope is real,how about just implementing mangohud and vkbasalt first,and bringing gamescope later when this issue is fixed?

**Comment by orowith2os** [comment]
This issue might be of some use: https://github.com/flatpak/flatpak/issues/5105

**Comment by mirkobrombin** [comment]
Following https://github.com/flatpak/flatpak/issues/4046

**Comment by lohothrone** [comment]
hello!
can i write it here or should i open another issue?
anyway, i have some problems with these flatpak packages or whatever, on mine desktop pc i have those runtime switches (archlinux, bottles installed from aur)
![Screenshot_20221229_225436](https://user-images.githubusercontent.com/121639545/210005426-5b65b140-9e14-43e8-9713-41b8e72661d5.jpeg)
but on mine steam deck (which install bottles from flatpak) those switches is missing (i suppose it's because that flatpak packages needs to be isntalled), after installing `com.valvesoftware.Steam.Utility.gamescope` it make the "Steam Runtime" switch available
so the question is - how or which flatpak package should i install to have the "Bottles Runtime" switch available or what it's runtime includes? is that [it](https://github.com/bottlesdevs/components/blob/main/runtimes/runtime-0.6.yml) or what?

**Comment by TheEvilSkeleton** [comment]
Bottles Runtime isn't used in Flatpak, so it's hidden. If you get it from the distro repos, you should see this option.

**Comment by Perkolator** [comment]
Why was this closed? I don't see anything that would have fixed this. Several settings are greyed out and can't be selected, and there's no hints of how to enable them.

Also, how does the user know what flatpak versions to install?

```
$ flatpak install mangohud

Looking for matches…
Similar refs found for ‘mangohud’ in remote ‘flathub’ (system):

   1) runtime/com.valvesoftware.Steam.Utility.MangoHud/x86_64/stable
   2) runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/21.08
   3) runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/22.08
   4) runtime/com.valvesoftware.Steam.VulkanLayer.MangoHud/x86_64/stable

Which do you want to use (0 to abort)? [0-4]:
```

```
$ flatpak install vkbasalt

Looking for matches…
Similar refs found for ‘vkbasalt’ in remote ‘flathub’ (system):

   1) runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/21.08
   2) runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/22.08
   3) runtime/com.valvesoftware.Steam.Utility.vkBasalt/x86_64/stable
   4) runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/stable

Which do you want to use (0 to abort)? [0-4]:
```

And then there is gamescope:

![image](https://user-images.githubusercontent.com/53913724/225477210-81c0e61e-e4ab-4751-b074-ac17b0655715.png)

Is that normal?

It really would be nice to have some kind of instructions.

**Comment by TheEvilSkeleton** [comment]
If you hover on the cogwheel on each grayed out row, you'll see a little popup that tells you what to run.

**Comment by Perkolator** [comment]
> If you hover on the cogwheel on each grayed out row, you'll see a little popup that tells you what to run.

Oh, ok. Not the best implementation IMHO. I wouldn't use a tooltip for such information (and only on the buttons, the setting can be activated also by pushing the text part), especially when that tooltip instruction includes a lengthy string that the user needs to type manually to the terminal. Why not show that in the text area? Why not have a "copy install command to clipboard"? Why not have a button that would launch the install procedure in terminal?

**Comment by TheEvilSkeleton** [comment]
Good point. Can you open a new issue about this?
