### ISSUE TITLE
[AUR]: Libadwaita 1.2 released

### ISSUE THREAD

**Issue by EvoXCX** [bottlesdevs/Bottles#2018]
Hello,
Libadwaita 1.2 is officially released while waiting for it to be available on the official Arch repository.

Please be ready to update bottles on AUR repositories (To avoid this kind of depreciation you should avoid using bleeding edge libraries it's not good for users security, this is only my opinion)

Thanks for your work !

**Comment by TheEvilSkeleton** [comment]
We don't maintain Bottles from the AUR anymore.

Also, we needed libadwaita beta to avoid delaying libadwaita adoption. Bottles is a big program so we need to start earlier than everyone else to complete porting as soon as other libadwaita apps. Otherwise we'd be stuck porting a larger codebase for a longer time and we'd be late too.

We use Flatpak by default, partially for security purposes. We unallow all directories except `xdg-download` and a few unimportant directories. Even if the library is insecure, it can't do much thanks to sandboxing. Distros are free to package our apps but it's on them if things go south.

**Comment by mirkobrombin** [comment]
Going deeper: the AUR package is no longer officially supported by Bottles but is still managed by me and 2 other guys to ensure it is packaged properly. The support (after the update) will be provided directly on the AUR by us packagers and we will be the ones to move the reports to GitHub when these are not caused by the package but by Bottles itself.

This repository is dedicated exclusively to Bottles intended as code and the main package (Flatpak). Our intention has been for years to officially support AUR too but we couldn't get the Arch Linux community to listen to us and despite the many announcements, people didn't understand why we chose to update libadwaita to that version and freeze the AUR package. , therefore a dedicated support was also necessary to avoid having to manage multiple issues not really related to Bottles.

As soon as libadwaita 1.2.0 comes out we will update.

**Comment by EvoXCX** [comment]
Thanks for the clarification @mirkobrombin , but @TheEvilSkeleton please don't say that flatpak is secure because the developers themselves can't handle the security issues even though it's been open for several years, I'll let you analyze it by yourself :)
https://flatkill.org/

**Comment by TheEvilSkeleton** [comment]
This article does not apply to Bottles flatpak. I already made a response on my website as well.
