### ISSUE TITLE
[Request] Back buttons in onboard

### ISSUE THREAD

**Issue by Kekun** [bottlesdevs/Bottles#211]
I'm using 3.1.2 from flathub IIUC.

When opening the app, I got greeted by a Welcome dialog that helps me present the concept of the app and complete its setup (that's great, I like it). but I have an issue with that dialog: it never lets me go back or quit the app.

![Capture d’écran de 2021-03-29 12-41-27](https://user-images.githubusercontent.com/2536339/112826454-478acf80-908d-11eb-9c05-1897fae0710c.png)

It'd like to have a Back button to read the previous pages, and maybe even a Quit button on the first page to be able to close the application if I don't want to install Wine: if I look only at the window, I'm stuck with the app open and no way to close it. Using [`HdyCarousel`](https://gnome.pages.gitlab.gnome.org/libhandy/doc/1.2/HdyCarousel.html) would help.

Or maybe even better: what's the point of having a tiny dialog with a big unaccessible and empty window behind it? Why not make the welcoming process part of the main window? That would make the app feel more like a GNOME app to me. We even have a pattern for that: the welcome page pattern, and you can easily implement it with [`HdyStatusPage`](https://gnome.pages.gitlab.gnome.org/libhandy/doc/1.2/HdyStatusPage.html).

**Comment by mirkobrombin** [comment]
Hi, the onboard dialog in Bottles v3 it is actually a forced step. Bottles unlike other programs requires the installation of two components that cannot be packaged together with Bottles itself for several reasons.Without installing these components you cannot use the application. The lack of a close and back button is actually an issue I haven't thought about.

Bottles v3 is an application that will only receive bugfixes and minor improvements, the current code has undergone major changes with the restyle, many elements have been replaced with those from libhandy but at the moment replacing the onboard with libhandy's carousel can take a long time. I prefer to spend this time working on v4 which has much cleaner and easier to customize code, reducing the risk of compromising the whole base with future updates (as happened from v2 to v3).

I'll add the quit and back keys to v3, where the former actually closes the main application.

I also tag @jannuary  who takes care of the graphic part of the project, so that he can find time to redesign the onboard for Bottles v4.

**Comment by jannuary** [comment]
> I also tag @jannuary who takes care of the graphic part of the project, so that he can find time to redesign the onboard for Bottles v4.

not he ;)

I believe the onboarding was a bit last minute decision that wasn't really thought through perfectly. Redesigning it to utilize HdyCarousel and colorful visuals is probably a good step for v4.

**Comment by Kekun** [comment]
@jannuary If you need someone to review the UI don't hesitate to ping me here or in any of the GNOME rooms we share (e.g. the libhandy room). :)

**Comment by mirkobrombin** [comment]
> > I also tag @jannuary who takes care of the graphic part of the project, so that he can find time to redesign the onboard for Bottles v4.
> 
> not he ;)
> 
> I believe the onboarding was a bit last minute decision that wasn't really thought through perfectly. Redesigning it to utilize HdyCarousel and colorful visuals is probably a good step for v4.

Sorry. Yeah I haven't spent much time on it

**Comment by jannuary** [comment]
> I also tag @jannuary  who takes care of the graphic part of the project, so that he can find time to redesign the onboard for Bottles v4.

My pronouns are they/them. Please revise your message.
