### ISSUE TITLE
[Request]: Remove "Select Dependencies"

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#2112]
### Tell us the problem or your need

At the moment, the "Select Dependencies" toggle changes the whole window. It is extremely laggy and slow, and can potentially introduce to crashes:

https://user-images.githubusercontent.com/50847364/192577318-89f4db90-f8de-47c7-aa2e-b32637894a80.mp4

### Describe the solution you'd like

https://github.com/bottlesdevs/Bottles/issues/2112#issuecomment-1259819990

### Additional context and references

Related to https://github.com/bottlesdevs/Bottles/issues/2102.

**Comment by mirkobrombin** [comment]
I think the whole feature should be removed. It is a very risky operation installing multiple deps in one row, e.g.:
- the wineserver can goes down while processing one dep, invalidating all the next
- some deps might incompatible with other deps, breaking the prefix in a non recoverable way if versioning is not enabled (despite the fine job we are doing on the background, it is not possible to prevent this, not without layers but that's a whole different topic which we will discuss soon in a metting)
- some deps are very complex and Bottles does a lot of things in the background, if one dep breaks compatibility with another one the entire process may freeze breaking the prefix
- some novice users can use all dependencies in one row because they think this is possible (we are actually allowing it), this in 99% of cases breaks everything and the user will blame Bottles

**Comment by Korabel47** [comment]
Hi. Thanks for your efforts to make this app!

Although you had already closed this issue, may I know what workarounds exist helping to avoid manually clicking on every single dependence to install? Each of them takes approximately 2 mins to install - on my machine.
I would appreciate a solution to speed up this process.

Best regards
