### ISSUE TITLE
[Bug]: bottles apparently is not recognizing my video card

### ISSUE THREAD

**Issue by Heus-Sueh** [bottlesdevs/Bottles#2150]
### Describe the bug

![image](https://user-images.githubusercontent.com/98482469/194763016-4ef25150-9536-48fd-b26d-d2156efa9d7b.png)

### To Reproduce

.

### Package

Flatpak from Flathub

### Distribution

Fedora 36

### Troubleshooting Logs

```shell
Version: 2022.9.28.1
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.14-200.fc36.x86_64
Distro:
    Name: GNOME
    Version: '43'
Disk:
    Total: 8347070464
    Free: 8346906624
RAM:
    MemTotal: "16,7\_GB"
    MemAvailable: "12,8\_GB"
Bottles_envs: null
```

### Display Protocol

X11

### Display Backend used by Bottles

X11

### Additional context

![image](https://user-images.githubusercontent.com/98482469/194763400-80e437e2-9d57-47c9-bd18-b08f1eaffba4.png)

**Comment by Dungeonseeker** [comment]
Check you don't have any per user or system env vars overriding Bottles. For example having $VK_ICD_FILENAMES set globally will override Bottles and even if its still correctly set it can still cause issues. Took me over a week to work out why no games would work in Bottles but everything else worked fine, after unsetting VK_ICD_FILENAMES it just worked and has continued to work ever since.
