### ISSUE TITLE
[Request]: Please sort the dependency list alphabeticallly

### ISSUE THREAD

**Issue by LiamDawe** [bottlesdevs/Bottles#2194]
### Tell us the problem or your need

The current Dependency list inside Bottles isn't sorted, and makes finding things to install quite annoying.

Could you please sort it alphabetically? It sure would make it better.

### Describe the solution you'd like

Sort the list by name.

**Comment by mirkobrombin** [comment]
You can also start typing to search

**Comment by LiamDawe** [comment]
That's good to know, but I still think it should be sorted alphabetically because it just makes more sense.

**Comment by mirkobrombin** [comment]
Looks like the dependencies list is already alphabetically sorted. Perhaps what strikes you as odd is that the installed dependencies are at the bottom of the list rather than mixed?

![image](https://user-images.githubusercontent.com/9479903/200680236-bab2dc3c-2aec-4ae7-b17d-7baf371732bb.png)

![image](https://user-images.githubusercontent.com/9479903/200680249-7ce83698-92ad-46e7-940a-24f085f70e50.png)

![image](https://user-images.githubusercontent.com/9479903/200680257-9230dcff-0551-4b77-92a5-defcff86c259.png)

![image](https://user-images.githubusercontent.com/9479903/200680266-2fff1d1d-9dee-4cb1-9423-fe822f95cf6d.png)

![image](https://user-images.githubusercontent.com/9479903/200680276-f031dbb0-827d-4a13-9c0a-ea20d452d60f.png)

![image](https://user-images.githubusercontent.com/9479903/200680287-08ac6b37-195e-4ed2-9f7b-5aa6f0275138.png)

![image](https://user-images.githubusercontent.com/9479903/200680294-6cbbf003-3b11-4bcc-a65f-304bbf686233.png)

![image](https://user-images.githubusercontent.com/9479903/200680321-bdd7cc7a-661a-49a8-8376-81de5691b29a.png)

**Comment by LiamDawe** [comment]
Huh, I was sure it wasn't...

**Comment by mirkobrombin** [comment]
Sometime magic happens :D
