### ISSUE TITLE
Disable package fetching at startup / Lazy Loading

### ISSUE THREAD

**Issue by duarm** [bottlesdevs/Bottles#2294]
everytime I open bottles, it takes around 10 seconds for it to open because of those package fetching, opening it without internet connection takes less than a second. I was wondering If there was a way to disable this and only fetch them manually, couldn't find anything on the options. Or perhaps a smarter mechanism, like fetching on background or fetching a date first, in order to check if all the packages need to be fetched again.

A manual option should be available tho, despite the chosen route, since some might not be confortable with the internet being accessed everytime a program is opened.

**Comment by mirkobrombin** [comment]
Related https://github.com/bottlesdevs/Bottles/issues/2057

**Comment by jannuary** [comment]
Unrelated. Even with an internet connection, it'd be nice to do package fetching less intrusively, which is what this issue is asking for.

**Comment by mirkobrombin** [comment]
The problem is the long time it takes. We should fix it and improve the offline check instead of introducing features that prevents the user from getting updated components/programs/dependencies and the report issues for what we already fixed.

Currently **the problem** is not related to our mirrors but the `urllib` library being slow fetching them for some reasons. There are better alternative out there which we should considerate. Again, providing a feature that let the user staying outdated is a bad practice in this case and I will never implement a feature like this since I don't even support local repositories or outdated ones.

Also, fetching a timestamp and the repositories (less then 20kb) takes almost the same time. Implementing this server-side require also more maintenance and more background tasks (cronjob? github actions?).

**Comment by Kinsteen** [comment]
How about fetching the repositories in the background, but if the user goes to download something it will "force-fetch" (ie wait for the background fetch to finish) to show anything? It would fix both problems, no?

**Comment by mirkobrombin** [comment]
As it is written now the project may require major changes, in fact not even the return from offline to online no longer works. I will try to investigate the code again to see if it is possible to implement it. That would be a good compromise.

**Comment by duarm** [comment]
> Again, providing a feature that let the user staying outdated is a bad practice in this case
Even so, give me the choice, I sometimes proxy my connection through some really slow peers, or I'm just not willing to make a request everytime a program is opened.

**Comment by duarm** [comment]
yeah, I'm running bottles with `firejail --net=none`

**Comment by duarm** [comment]
#2412 begins the work on this, thanks

**Comment by Kinsteen** [comment]
The work is now upstreamed
