### ISSUE TITLE
Too many papercuts at first try to stick to Bottles

### ISSUE THREAD

**Issue by romanovzky** [bottlesdevs/Bottles#2310]
Hi there,

I was trying out bottles to run a work related program. I opened it up, made a bottle, installed the program. Then the problems started. The program installer, a company made special use little application, didn't appear on the list. "Ok", I thought, "there's an add shortcut button". I clicked on "add shortcut" and the file browser opens up in my last opened directory (incidentally, ~/Downloads). "Where's the prefix?" I wondered. Looked for all possible places that came to mind and gave up. "Maybe it's this sandbox thing, let me install a non-flatpack distribution" (I'm running an arch-based distro, so I have multiple Bottles distributions available to me). I reinstalled the app using different variations of Bottles, and still can't understand how can I add a shortcut for an executable inside the prefix...

I consider myself mid-veteran with Wine. I've used it first around de mid 00s, so I have a couple of decades of experience in running Wine with different abstractions. Bottles promised me a GUI where everything would be intuitive, and I can't make a single program run.

As it stands, I can't recommend Bottles to anyone new to Wine and/or Linux, which I believe means that Bottles failed for me in its use case.

Still decided to leave you with feedback of my papercut experience, as I'm sure many new comers to Wine and Linux will have a similar, or worse, experience to mine.

Best

**Comment by mirkobrombin** [comment]
Hi, this is a ticket platform not a forum. Please post your thoughts on forums.usebottles.com

Btw to reply to your problem:
- Wine (the backend used by Bottles to run Windows apps on Linux), doesn't support any Windows apps, that's thy winedb.org was created
- About the program not being listed, please read the [documentation](https://docs.usebottles.com/bottles/programs)
- About "Where's the prefix?", there is a dedicated button on top of the details view, inside the context menu
- About the file dialog not showing the prefix by default: this is a technical limitation of the [FileChooseNative](https://docs.gtk.org/gtk4/class.FileChooserNative.html), we can't simply use the "standard" File chooser since Bottles is sandboxed and a portal is needed to access files outside the sandbox
- About "I reinstalled the app using different variations of Bottles", we only provide support for the Flatpak
- About "still can't understand how can I add a shortcut for an executable inside the prefix", with the following points in mind, refer to the [documentation](https://docs.usebottles.com/bottles/programs)
- About "Bottles promised me a GUI where everything would be intuitive, and I can't make a single program run.", I don't understand how the UX / UI of the program centers with Wine's inability to start it or the user not finding a path using the system file manager
- About: "As it stands, I can't recommend Bottles to anyone new to Wine and/or Linux, which I believe means that Bottles failed for me in its use case. Still decided to leave you with feedback of my papercut experience, as I'm sure many new comers to Wine and Linux will have a similar, or worse, experience to mine", this sounds more rude then helpful to be honest.

My suggestion is: read the documentation and report bugs when something doesn't works as expected, providing details more then words.


Cheers.

**Comment by romanovzky** [comment]
I really didn't mean to come across rude... I was providing feedback of an experience which you might want to be aware of, I was not looking for support nor start a discussion. I couldn't find those issues, I guess that looking for "add shortcut" (as it stands in the GUI right now) was a bad keyword to find my problem.

The sandboxed implementation seems to be quite obstructive to some functionality that I find important for my use-cases. This case was for a work app that doesn't fall within the assumptions carried out by Bottles, namely that it makes lnks, etc. But for gaming I often need easy access to the installation folder for modding, editing, etc. So in the end it's just the case that Bottles doesn't suit my needs, but I'm sure it'll fulfil many other users and more power to them and great work from you!

I'm sorry if my post landed as rude, I just thought that "Feedback" could be used to provide feedback of a bad experience (or in my case, a misplaced expectation of the use-case). In my experience papercut experiences are important to register, even if they fall outside the scope and purpose of an app to better recognise the use-cases and target audience, both in comercial and open source projects.

That being said, I do thing Bottles is a great idea, and I'm just sad it doesn't cover my needs.

Cheers

**Comment by jannuary** [comment]
Good etiquette regarding issue trackers is posting actionable bug reports or feature requests with steps on how to replicate the issue and problem expressed by the issue. Ranty text walls are not actionable and do not help solving whatever the problem is.
