### ISSUE TITLE
library: Design issues

### ISSUE THREAD

**Issue by sophie-h** [bottlesdevs/Bottles#2458]
I think the library feature is no longer experimental, right?

Found the two following things:

- The search button has no effect
- With programs having no ... image (?) the library looks like this

![image](https://user-images.githubusercontent.com/3466497/209887110-f2011a87-922b-4b32-ab23-c133662cb376.png)

**Comment by TheEvilSkeleton** [comment]
Can you provide an example of a program that doesn't have an image?

**Comment by mirkobrombin** [comment]
As I suggested months ago, we need a placeholder

**Comment by MrQuerter** [comment]
> Can you provide an example of a program that doesn't have an image?

@TheEvilSkeleton One of the most popular ones is 7-zip. It doesn't have any assets in SteamGridDB which makes Bottles not show anything at all.

> As I suggested months ago, we need a placeholder

What about something super simple like Heroic Launcher has?
I made a little test cover:
![dark](https://user-images.githubusercontent.com/84787215/210873041-065ff5ab-3f78-4bf0-b41d-c9eebb21a219.png)
![light](https://user-images.githubusercontent.com/84787215/210873092-15487f1e-3751-409b-90ae-f82d55591f82.png)
The left one is transparent and the 2nd is a diagonal gradient of 2 purple colors from GNOME HIG palette. Logo and text on both taken from the website repo and placed in a way that the UI after hover doesn't overlap them.

**Comment by TheEvilSkeleton** [comment]
@mirkobrombin what are your thoughts on using @MrQuerter's cover? I really like it.

**Comment by jannuary** [comment]
It definitely shouldn't have a generic "Bottles" image.

**Comment by TheEvilSkeleton** [comment]
What should it be then?

**Comment by mirkobrombin** [comment]
> It definitely shouldn't have a generic "Bottles" image.

I agree with this. Library entries as nothing to do with Bottles. I'd like to see a general "No cover" or just an empty one.

**Comment by MrQuerter** [comment]
Is this one closer?
![dark2](https://user-images.githubusercontent.com/84787215/211079898-000f27e8-cd57-4120-a72c-c7c5edf96f9c.png)
![light2](https://user-images.githubusercontent.com/84787215/211079923-cd0935e5-f1e2-4cbf-8404-bee796268e70.png)
Yes, I know it's technically empty cd case not an empty cover, but I feel like it conveys the idea. Also made elements of it transparent so it can take advantage of dark and light mode.

**Comment by jannuary** [comment]
> What should it be then?

We can get the app's icon, right? The earlier version displayed it in the library, I don't see why it shouldn't be used for unknown apps, just on a bigger scale

**Comment by MrQuerter** [comment]
> We can get the app's icon, right? The earlier version displayed it in the library.

Oh, right. Forgot about it. Still 2 cases to consider:
1. What if the program icon is really small? For example old software which has icons in max size of 32x32 pixels. (or even smaller). You can see in icons folders that Bottles does upscale it in some way, but it looks heavily blurred since it makes it into 256x256 .png (also I don't know which icon exactly does it take since some .ico files can have more icons inside. It seems to take the one on the first layer when you open in GIMP)
2. What if the program doesn't have any icon at all? I tested it and as you can predict Bottles doesn't prepare any empty icon in icons folder so it would still be empty.

Another thing. Where should the icon be displayed now? Having it in programs list would be also great, but let's focus on the library first.
If we place it next to the name and bottle name then it would only be visible when you hover the library entry. You could also place it above the "launch" button, but I have no idea if it's possible to do it like that in the UI.

**Comment by mirkobrombin** [comment]
> * The search button has no effect

The search function wasn't even planned for the library and that button comes from the list of bottles. I will make a fix shortly to resolve and we will evaluate the search integration for the library in the future.

**Comment by TheEvilSkeleton** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/50847364/227643641-47f05719-8b87-4967-86f4-6224c186b58d.png)

From https://github.com/bottlesdevs/Bottles/pull/2816
