### ISSUE TITLE
[Bug]: Inconsistent capitialization can lead to broken/missing runners

### ISSUE THREAD

**Issue by samfundev** [bottlesdevs/Bottles#2850]
### Describe the bug

When Bottles downloads certain runners, their capitalization is slightly different from what Bottles was expecting and so will lead to the confusing behavior and the runner not working correctly.

Bottles shouldn't be tripped up by this capitalization mismatch. A possible solution would be renaming the resulting runner folder whatever name Bottles expects it to be.

### To Reproduce

1. Download the ge-proton7-51 runner
2. Click on "Browse files" for the runner
3. Bottles can't show the files, "OpenURI portal not installed"
4. Restart Bottles
5. Bottles no longer thinks ge-proton7-51 is installed
6. Rename the "GE-Proton7-51" runner folder to "ge-proton7-51"
7. Restart Bottles
8. Both problems are now fixed but the runner will no longer run ([Bottles is checking for "Proton"](https://github.com/bottlesdevs/Bottles/blob/775939488296fdb570856981cbfea59b663cf119/bottles/backend/wine/winecommand.py#L415))

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.10

### Debugging Information

```shell
Official Package: true
Version: '51.5'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-525-105-17/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-38-generic
Disk:
    Total: 16785584128
    Free: 16785416192
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 11.5GiB
Bottles_envs: null
```

**Comment by koplo199** [comment]
There is two bugs here.

The first one is on the [component](https://github.com/bottlesdevs/components) side and match what you described: there is a mismatch between the component name (lower-case) and the extracted component directory (which contains capitalized letters). 
Concerning the fix: should we change the extracted folder name to lower-case, or the component name to include those capitalized letters? I don't know, I'll submit a PR there based on the decision of a maintainer.

The second bug is on the Bottles side and is actually identical to what's described in #2593, so the fix would be the same. What is happening is that the backed still uses the name of the component to decide if a runner is Proton or Wine, instead of what's included in its manifest. And it causes issues with Wine runners which contains `[pP]roton` in their name, like Kron4ek's [wine-proton-8.0-1-amd64](https://github.com/Kron4ek/Wine-Builds/releases/tag/proton-8.0-1) or GloriousEggroll's [Wine-GE-Proton7-43](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-43).

**Comment by Perkolator** [comment]
I just had this problem. Installing "GE Proton" version "ge-proton8-6" creates a "GE-Proton8-6" folder (notice the uppercase letters, all other runners are installed in lowercase letter folder names). After install, clicking the folder icon next to the version does nothing. Exiting Preferences and opening it again, the "ge-proton8-6" now only shows the install button. If clicked, it actually **removes** the previously created "GE-Proton8-6" folder. And again after this "install", it shows the folder icon to browse the files, but of course it doesn't work now either because the folder was removed.
