### ISSUE TITLE
[Question] How do you select a different language?

### ISSUE THREAD

**Issue by AtFreezingPoint** [bottlesdevs/Bottles#2852]
I mean, either i have missed the setting within the application somehow or it is somehow hidden? I know there exist different languages for the Bottles project but i was not able to find the place to change into them (be it for testing purposes only) and i'd either like to know where they are or suggest a "change language" setting or something...

**Comment by jannuary** [comment]
There's no way to change the application language. You can change the locale used by Windows applications in the bottle settings.

**Comment by AtFreezingPoint** [comment]
> There's no way to change the application language (and it's not likely there ever will be one). You can change the locale used by Windows applications in the bottle settings.

Well then what is [this](https://github.com/bottlesdevs/Bottles/blob/main/po#readme) link that's litterally the first thing you see on the main readme page?

**Comment by jannuary** [comment]
Translations. Bottles will follow your system language, but there's no separate setting.

**Comment by MrQuerter** [comment]
> There's no way to change the application language (and it's not likely there ever will be one).

Can we have some explanation why? Last time it was at least planned: https://github.com/bottlesdevs/Bottles/issues/708 (Don't know why it's closed as completed when it wasn't implemented.)

> I know there exist different languages for the Bottles project but i was not able to find the place to change into them

The dev said that in the meantime you can force it using environment variable. You can use Flatseal for that and put for example `LANGUAGE=en` in Environment section. Though I wish it finally gets added to settings.

**Comment by jannuary** [comment]
There's really no reason for an app to have a different language from the rest of the system — so we do not feel it is justified to add an additional moving part we would need to perpetually maintained for that. In addition, I am not familiar with any other GNOME apps in which "not following the system language" is a feature that exists.

The issue you linked was closed by Mirko, since location selection was implemented, which just got tacked on to that issue.

**Comment by AtFreezingPoint** [comment]
> There's really no reason for an app to have a different language from the rest of the system — so we do not feel it is justified to add an additional moving part we would need to perpetually maintained for that. In addition, I am not familiar with any other GNOME apps in which "not following the system language" is a feature that exists.
> 
> The issue you linked was closed by Mirko, since location selection was implemented, which just got tacked on to that issue.

Pfff... Really hate GNOME stuff that act proprietary as if they were above everything else, why can every application not have this setting like in pretty much every KDE made application?

![image](https://user-images.githubusercontent.com/70336977/233868085-70a79ca5-c37b-471c-ac31-31a52066e484.png)

This is exactly one of the reasons why people that use KDE stick with it (they **get the choice** to be able to do whatever they want)  and you guys will be supporting the GNOME dev teams decision like that? Keeping users in a bubble for no apparent reason?

**Comment by caugustin** [comment]
> The dev said that in the meantime you can force it using environment variable. You can use Flatseal for that and put for example `LANGUAGE=en` in Environment section. Though I wish it finally gets added to settings.

That's the solution I was searching for! Why isn't it nowhere to be found in any documentation (I'm aware of)? At least this could be part of the help pages.

And there are many reasons why a specific application needs to run in English: This is the language used in communication and in most content online! If I want to search for a solution online, I need my Bottles' GUI to be English (and it corresponds better to the "inner workings", so that I can get an idea what I'm searching for).

Besides, the German translation is full of holes, many areas are completely English or a mix of German and English names/descriptions. I can deal with it, but I prefer to operate in one language (less cognitive load, I'm 60+ and it shows ;-)).
