### ISSUE TITLE
[Request]: Add BlueStacks support

### ISSUE THREAD

**Issue by WindowxDeveloper** [bottlesdevs/Bottles#2913]
### Tell us the problem or your need

So, Android is based on Linux. It technically is or isn't a Linux distribution (depending on your view), but what is ironic is Linux hasn't got a good Android emulator/compatibility layer. Anbox worked for a while, but it gets buggier, while Waydroid is still limited, while Windows already has native Android support.

### Describe the solution you'd like

So I'd like to request to add support for BlueStacks and/or Genymotion to make Linux gaming a tad easier. After all, we'd love to bring Android back to Linux. 

### Other solutions?

Maybe we could use a VM to work.

**Comment by jannuary** [comment]
Way out of scope for Bottles, and besides, BlueStacks app player is not only proprietary & freemium, but it also installs a crypto wallet against one's consent — which is not something we want to be promoting.

**Comment by kuromaku001** [comment]
i agree linux emulators sucks

**Comment by kuromaku001** [comment]
> 

how is it out of scope android emulators are related to gaming !

**Comment by SUFandom** [comment]
Android Emulators are sometimes difficult to work with on a specific stuff under linux, of course AE on Windows (third party and main) are great in their own (except some third party emulators that are tad suspicious and has Chinese app running in background, _ehem, memu during 2018 if I reckon_) 

And Android Emulators for Linux are just best for Devel projects (Developing apps) rather than gaming in the main part. If I also remember, I tried gaming takt. Op Symphony on Waydroid and Vulkan can't pass through for some reason even if it's detected by AIDA last month (probably an Intel issue about pass-thru)

Let's just hope for Waydroid to advance through, as I recall, Genshin Did not work on waydroid before until the method of launching it was found under Waydroid shell, almost 2 years since the issue (probs)
