### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by ghtesting2020** [bottlesdevs/Bottles#2935]
did the team moving on to vanillaos kill this project? tickets aren't being looked at anymore, releases went from 2 weeks to months.

**Comment by Eonfge** [comment]
I'm afraid so, since some maintenance tasks are clearly not done. You can also see that they stopped packaging Wine with version 7.20, which was released in October 2022.

I would recommend Q4Wine:

https://flathub.org/en-GB/apps/ua.org.brezblock.q4wine

It's less advanced but it doesn't rely so much on custom components. Bottles was very ambitious with doing things differently, but that also meant that they have to do a lot of groundwork themselves. Q4Wine is simpler but as such, even without UI updates the core of the system is still updated routinely.

**Comment by Eonfge** [comment]
This is just not a very good showing, and I hope that the developers of Bottles can make a public announcement related to their projects' status. 

Ideally they flag the Flathub as deprecated, until they find the time or volunteers to contribute. Doing nothing, will just leave people hanging with a slowly decaying wine-util that doesn't have the maturity as its competitors: Bottles is in many ways still Beta and this only exacerbates the problems of a Beta tool. 

_Don't get me wrong. Open Source development is hard and ungrateful work... With the 3+ years of Flathub project maintenance, I know what it is to be burned out or pre-occupied. This just isn't the way to deal with it._

**Comment by Xalalau** [comment]
It's a shame, in my opinion Bottles is the best solution to deal with Wine. I have no way of replacing it satisfactorily.

**Comment by jannuary** [comment]
**There has not been any intention to discontinue or otherwise abandon Bottles.** While we cannot keep up the pace due to personal reasons, that does not imply that Bottles is dead — just that updates in the near future will be more slow and more focused on bug fixes.
