### ISSUE TITLE
[Request]: ARMHF Flatpak Version

### ISSUE THREAD

**Issue by WuShufei** [bottlesdevs/Bottles#2951]
### Tell us the problem or your need

There is no armhf package in Flatpak.  Thus your lovely doohickey cannot work on Raspad 3 running Raspbian on Raspberry Pi 4B and the heaps and heaps of other arm devices, with more every day.

### Describe the solution you'd like

Please build a working armhf flatpak.

### Other solutions?

Or, if needful to build manually, a way to do so if possible without inapplicable i386 Gnome doohickeys.

**Comment by penguinpee** [comment]
> There is no armhf package in Flatpak. Thus your lovely doohickey cannot work on Raspad 3 running Raspbian on Raspberry Pi 4B and the heaps and heaps of other arm devices, with more every day.

You may need to switch to a 64-bit OS. The RPi 4 supports aarch64. In Fedora for instance, 32-bit armhf has already been retired.

**Comment by orowith2os** [comment]
32-bit ARM will likely never happen for desktop apps like this, it's a fair bit limiting and the Freedesktop runtime hasn't supported it since 19.08 I believe.

64-bit ARM, on the other hand, is more doable, and there's been work within Wine (by Codeweavers) to put something together to run x86 apps.
