### ISSUE TITLE
org.winehq.Wine.* Flatpaks?

### ISSUE THREAD

**Issue by Perkolator** [bottlesdevs/Bottles#2969]
Could somebody explain why these Flatpaks are needed with the installation of Bottles:

- org.winehq.Wine.DLLs.dxvk
- org.winehq.Wine.gecko
- org.winehq.Wine.mono

I don't know about the `gecko`, but isn't `dxvk` installed separately from GUI as a "dll component", and `mono` installed from GUI as a "dependency"?

EDIT: Forgot to add; doesn't the "runners" include Wine already?

Yesterday there was an update to the `org.winehq.Wine.DLLs.dxvk` and [it seems to be updated very rarely](https://github.com/flathub/org.winehq.Wine.DLLs.dxvk/commits/branch/stable-22.08). Just got me wondering why these are installed.

Many thanks!

EDIT2: Forgot one thing more; are these org.winehq.Wine Flatpaks for the "mysterious" `sys-wine-8.0` runner that can be only found from the runner setting of a bottle (not in preferences->runners)?

**Comment by orowith2os** [comment]
These are, indeed, for the sys runners. You normally get them from Bottles (via external sources), but you always have the sys runners as a fallback.

Thinking about it, do we even *need* sys runners? Traditional distros aren't supported anymore, and it probably makes more sense to use Wine via the built-in Wine dependency management system.

**Comment by koplo199** [comment]
@orowith2os Maybe making them optional would be a solution? Removing:
https://github.com/bottlesdevs/Bottles/blob/9132667ae41a04769b286a09471306ba4deed980/com.usebottles.bottles.yml#L4-L5
But keeping:
https://github.com/bottlesdevs/Bottles/blob/9132667ae41a04769b286a09471306ba4deed980/com.usebottles.bottles.yml#L30-L32
Would still detect sys runners if the user installed them manually, but would not install them automatically alongside Bottles. This would spare `~300 MB`, which is not negligible:
```
flatpak list --columns=name,size | grep -e "Mono" -e "Gecko" -e "DXVK"
DXVK	22,1 MB
Gecko	110,3 MB
Mono	245,1 MB
```
Finally, whether they're installed or not, on the first launch Bottles still installs its own version of DXVK, vkd3d-proton, Wine (Soda) and use them by default instead of the sys ones, so it really wouldn't change anything in that regard. If it's something that can be considered I could easily add that to #2964.

**Comment by MrQuerter** [comment]
Dropping org.winehq.Wine was already suggested. Ask main dev if the situation changed.
https://github.com/bottlesdevs/Bottles/issues/2026

**Comment by koplo199** [comment]
I see, nice catch @MrQuerter. Better drop the idea then.

**Comment by mirkobrombin** [comment]
> Dropping org.winehq.Wine was already suggested. Ask main dev if the situation changed. #2026

The situation did not changed.
