### ISSUE TITLE
How to uninstall a program that does not uninstall itself??

### ISSUE THREAD

**Issue by BarbzYHOOL** [bottlesdevs/Bottles#2995]
How to uninstall a program that does not uninstall itself??
I click on the "..." then "Uninstall" and it does absolutely nothing

**Comment by Perkolator** [comment]
Try this:

- From a bottle, scroll down to `Tools` section and `Legacy Wine Tools` and then...
- Open `Uninstaller` and uninstall the program. If the program is not listed there, try...
- Open `Explorer`, then browse to the folder where the program is installed and try to locate an executable that looks like an uninstaller and start it.

I only install 1 game/program per bottle (because I've found out that if you have to change the settings of a bottle many times, something might go wrong with the whole bottle environment which affects running the programs/games, and because there is a problem with running programs from a same bottle with created "desktop entries" (I haven't had the time to report this yet)). It's easy to "uninstall" in this situation = just delete the whole bottle.

**Comment by BarbzYHOOL** [comment]
thanks bruh, uninstaller worked

do you know how can I make one app not showing shows too? using similar type of tricks

**Comment by Perkolator** [comment]
> not showing shows

I don't understand what you mean.

**Comment by BarbzYHOOL** [comment]
an app that does not appear in the list in my bottle

How to make it show up? manually

**Comment by Perkolator** [comment]
![image](https://github.com/bottlesdevs/Bottles/assets/53913724/dbe62ad9-44b4-4289-8780-498a4f286bf3)

There is a help text, and in case of the program list already having a program in it, there's still a big `+ Add Shortcuts...` button there. Don't take this the wrong way but you need to just learn to use the basic stuff of programs by yourself, explore and try things with a new program and learn what it can do. Please close this issue since the original problem was solved. Thanks.

**Comment by BarbzYHOOL** [comment]
i just found it by myself while installing another program, can even rename the shortcut

there is literally 0 help text nonetheless + this program is really weird (like everything related to wine)
dude, i'm a dev too...

**Comment by Perkolator** [comment]
> there is literally 0 help text nonetheless

If you look at the screenshot I posted, when the program list is empty, there IS a help text.

**Comment by BarbzYHOOL** [comment]
it wasn't empty

**Comment by git-tiger** [comment]
Can I delete the installed program folder in Bottles container folder?
