### ISSUE TITLE
[Request]: Queue installing dependecies

### ISSUE THREAD

**Issue by larina3315** [bottlesdevs/Bottles#2997]
### Tell us the problem or your need

Currently, when you install a dependency in Bottles, you are unable to Queue any other dependency to be installed after the current dependency has finished installing. As most WineHQ and other 3rd-party guides require you to install multiple dependencies, it is frustrating to sit down infront of my computer and wait until the current dependency has finished installing so i can manually select another one for installation.

[Screencast from 2023-07-27 10-05-59.webm](https://github.com/bottlesdevs/Bottles/assets/138502262/ea4603e0-1f65-4791-a8aa-154daa03cc9e)

Here's a screen recording of the issue i was talking about, instead of marking all the vcredist* files for install and going out to get some coffee, I have to frustratingly sit down and wait for each one of them to finish installing.

### Describe the solution you'd like

Add an Queue system so an user can mark multiple dependencies for installation while aforementioned user goes out to get some coffee.

**Comment by mirkobrombin** [comment]
We used to offer such feature but then removed since it's harmful in the wine context, a lot of users suggested/reported to install all the dependencies to achieve better compatibility but half of the packages in that list conflicts with each other, plus some dependencies takes minutes to install and since there is no way to stop that process, some users could just kill the app, resulting in broken installations so we opted to remove that feature.

**Comment by larina3315** [comment]
> @mirkobrombin to be completely sure, you aren't confusing this with installing several dependencies at the same time? Those are two different issues, and are/could be handled differently.

Just to be clear, I was suggesting having a Queue. e.g. Dependency #2 starts installing AFTER Dependency #1 has FINISHED installing, not simultaneous installations.
