### ISSUE TITLE
Offline bottles to keep semi-suspicious exes in check.

### ISSUE THREAD

**Issue by Sinaaaa** [bottlesdevs/Bottles#3015]
### Tell us the problem or your need

Bottles is amazing, to me it's a game changer over Lutris's weird and inflexible interface. The only feature I miss for the app to be feature complete for my needs is offline bottles..

Keep up the good work!

### Describe the solution you'd like

"Force Offline" option at Bottle creation to prevent the apps in the prefix from going online.

**Comment by mirkobrombin** [comment]
Hi. We can't really support this since Windows apps works in different ways, we can't provide a way to prohibit them from launching. I can just assure you that everything is running under the flatpak sandbox (bubblewrap) and we are working on our own sandbox for fine tuned permissions (you can already test it in Bottles -> preferences -> experimental.
