### ISSUE TITLE
[Request] Winetricks option for individual bottles

### ISSUE THREAD

**Issue by LifeWatcher123** [bottlesdevs/Bottles#307]
Some games need specific programs to be installed using winetricks to run properly. It would be nice to have the option to run winetricks commands on specific bottles.

**Comment by mirkobrombin** [comment]
https://github.com/bottlesdevs/Bottles/blob/master/README.md#where-is-winetricks-rage4

Bottles is not your usual wine prefix manager. We want to offer a product that works and offers a complete and integrated user experience. To do this we have to compromise and face complex decisions, such as not to integrate external tools such as winetricks as this drastically worsens the user experience. There are also several other aspects to consider, for example having to depend on these tools and the different adaptation to their functioning and updating during their life cycle.

It should also be borne in mind that Bottles is not born with the concept of one software per bottle but rather a bottle for several software.Bottles from v2 integrates its own dependency installation system, accessible from the s bottle Since v3 the system has been expanded with a community driven repository to which anyone can collaborate ee With Bottles v4 we are working on installer support, integrated with the Bottles dependency system with which it is possible to install dependencies and tricks This system will also allow us to understand, during the installation of a software through one of our installers, if the bottle and the software already installed inside it are compatible. with the new software we are going to install.

There are so many managers of wine prefixes and I am aware that many expect a lot from Bottles (perhaps because of its UI and simplicity) but I believe that integration with winetricks does not help the final purpose and that it can become an obstacle (also incompatible) to the final dependency system that we will see in Bottles v4.

Not integrating it in Bottles does not mean however that it is impossible to use it, Bottles bottles are prefixed anyway, you can use it outside of Bottles.

Let me know if you have any other doubts 🙂

**Comment by LifeWatcher123** [comment]
Thanks for the explanation. It's always a treat to read technical stuff like this. 

I do have one question, though: what is the Bottles' way to install some dependencies? There is a Dependency tab for Bottles, but what should I do for some unlisted dependency that I need?

**Comment by mirkobrombin** [comment]
You can manually install using its executable installer o place the DLL inside your prefix. The dependencies section is based on this repository: GitHub.com/bottlesdevs/dependencies

If you decide to include a dependency for all users, you can create its manifest and publish it in the repository.
