### ISSUE TITLE
Games not working

### ISSUE THREAD

**Issue by ziomek64** [bottlesdevs/Bottles#310]
Okay so the games are not running for me, i created a gaming bottle, tried newest lutris wine and its not working for me. One games is just not starting the other says dx11 is not there or something like that. These games works for me under lutris. But I wanted to try Bottles. I'm kinda new so linux to would appreciate help, i don't know if its on my end or the bottles app

I tried arch and flatpak version of bottles

**Comment by mirkobrombin** [comment]
Please follow the bug report template.

**Comment by ziomek64** [comment]
Installation

    Method: arch, also tried flatpak
    Version 3.1.13

As I said I tried running some games and they are not running at all. One of them throws windows error about dx11.  Using newest proton ( also tried lutris wine ) and dxvk 1.8.1. What information do you need, how can i get it for you 

Running clean arch with gnome

**Comment by ziomek64** [comment]
`2021-06-12 12:49:13 INFO: Running an executable on the wineprefix …
esync: up and running.
0080:err:module:open_builtin_so_file failed to load .so lib "/home/cryptozio/.local/share/bottles/runners/Proton-6.9-GE-2/files/lib64/wine/x86_64-unix/wineusb.sys.so"
0080:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
`
Thats what i'm getting in the console
Also getting this, idk if its wine or my game:
`Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date
drivers for your graphics card and have not disabled
3D acceleration in display settings.
InitializeEngineGraphics failed`

This is on newest flatpak

**Comment by mirkobrombin** [comment]
The issues you are reporting seem specific to Wine rather than Bottles.

Most Windows software needs tricks and dependencies in order to function. Lutris offers installers that automate the tweaking process of a wineprefix in order to run that software (if supported), this by installing dependencies, changing Windows version, adding or modifying DLLs via override or physically, installing DXVK, enabling esync or fsync or wine sync etc.

Bottles will support this function from v4, where it will implement its own installers that will automate the process. Until then you can proceed manually, looking on WineHQ and ProtonDB for the dependencies to be installed and the changes to be made to the bottle to run that software.

Let me also say that if you are looking to run a game, Lutris is light years ahead of Bottles and if that game is supported by their community (via installer) you should take advantage of it.

> Just a small note. From your log I also notice that the error is related to the absence of DirectX11. This actually does not need to be installed if you are using DXVK, as this tool itself provides the DLLs needed to take advantage of the Vulkan-based implementation of D3D9, D3D10 and D3D11. Also be careful to use DXVK with Proton as this is already implemented and active by default in Proton itself.

Other references:
- https://github.com/bottlesdevs/Bottles/issues/308
- https://github.com/bottlesdevs/Bottles/issues/214
- https://github.com/bottlesdevs/Bottles/issues/175
- https://github.com/bottlesdevs/Bottles/issues/133#issue-815846335
- https://github.com/bottlesdevs/Bottles/issues/307
- https://github.com/bottlesdevs/Bottles/issues/55#issuecomment-791735589

Let me know if I can help you in any other way or if you need more information 🙂

**Comment by androidfan-byte** [comment]
use DXVK, it fixed for me

<img width="592" height="290" alt="Image" src="https://github.com/user-attachments/assets/51921262-0e29-4863-8931-a53267f8ce34" />
