### ISSUE TITLE
[BUG] Virtual desktop setting doesn't work

### ISSUE THREAD

**Issue by makeworld-the-better-one** [bottlesdevs/Bottles#315]
Thanks a lot for creating and maintaining Bottles! It's a great application and makes using Wine fun. Wine is tedious and annoying for me to use normally. Thanks to Bottles I can just get stuff done on Linux.

**Describe the bug**

If you open a bottle, then go to the Preferences tab, there's an option called "Use a virtual desktop".

![image](https://user-images.githubusercontent.com/25111343/122305921-9b12f980-ced5-11eb-8b2c-6e2d7e751a3a.png)

This setting doesn't actually change anything, even after rebooting the bottle (not sure what rebooting does in this context). The fact that the setting doesn't affect the bottle can be seen by running the desired EXE again, but also by opening the Wine config application.

![image](https://user-images.githubusercontent.com/25111343/122305968-b1b95080-ced5-11eb-8c9f-4ba58e11f93d.png)

Going to the Graphics tab will show that the virtual desktop is not enabled.

![image](https://user-images.githubusercontent.com/25111343/122306086-df05fe80-ced5-11eb-8668-69b0bc20e38c.png)

The only way I've found to make the virtual desktop setting work is to enable it from the Wine config.

**Installation**
 - Method: Flatpak
 - Version: 3.1.14 according to the in-app info, but Flatpak says I've installed version 3.1.11

**To Reproduce**
1. Create a bottle
2. Run an EXE and observe how there's no virtual desktop
3. Enable the virtual desktop setting in the GUI
4. Reboot the bottle
5. Run the EXE again or open the Wine config and observe how there's still no virtual desktop

**Expected behavior**

The virtual desktop GUI toggle and setting should affect the Wine config.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by mirkobrombin** [comment]
Thanks a lot for the kind words, really appreciate.

The virtual desktop toggle is currently limited, Bottles applies the change to the registry but this only comes into play when all processes in the wineprefix are terminated. Initially I was thinking of forcing it to stop once the option is selected but this may interrupt the user's workflow.

One of the big limitations of Bottles v3 (and every other wineprefix manager I guess) is the poor integration with Wine. Each action in fact requires access to winecfg or command line in order to be applied "in the right way".

Fortunately this problem is about to be solved in Bottles v4, thanks to our [libwine](https://github.com/bottlesdevs/libwine) library, which is a complete wrapper for Wine and wineprefixes. This allows us for example to correctly set the [virtual desktop mode](https://dev-docs.usebottles.com/libwine/wine.html#libwine.wine.Wine.set_virtual_desktop), toggle the [window managed mode](https://dev-docs.usebottles.com/libwine/wine.html#libwine.wine.Wine.set_window_managed), [choose the Windows version](https://dev-docs.usebottles.com/libwine/wine.html#libwine.wine.Wine.set_windows), set the [decorations](https://dev-docs.usebottles.com/libwine/wine.html#libwine.wine.Wine.set_decorations), set the [fullscreen mode mouse capture](https://dev-docs.usebottles.com/libwine/wine.html#libwine.wine.Wine.set_fullscreen_mouse_capture), change the [DPI](https://dev-docs.usebottles.com/libwine/wine.html#libwine.wine.Wine.set_dpi), manage the [registry keys](https://dev-docs.usebottles.com/libwine/wine.html#libwine.wine.Wine.reg_add), the [DLL overrides](https://dev-docs.usebottles.com/libwine/wine.html#libwine.wine.Wine.override_dll) (in the same way that winecfg manages them ) and much [more](https://dev-docs.usebottles.com/libwine/wine.html#libwine.wine.Wine)..).

Since this is a substantial update (in fact a complete rewrite of the code from scratch), it will still take some time to implement it. So for now I ask you to be patient and remember to terminate every process for the change to the virtual desktop to take effect, otherwise to go via winecfg.

Other references:
- https://dev-docs.usebottles.com/libwine/wine.html#libwine.wine.Wine.set_virtual_desktop
- https://github.com/bottlesdevs/libwine#readme
- https://github.com/bottlesdevs/Bottles/issues/133

Let me know if you need any more information 🙂

**Comment by mirkobrombin** [comment]
There is a "kill" button next the restart one

**Comment by makeworld-the-better-one** [comment]
Oh okay, sounds good.

**Comment by mirkobrombin** [comment]
Ping https://github.com/bottlesdevs/LibraryWine/issues/1
