### ISSUE TITLE
[Bug]: Unable to find .yml files.

### ISSUE THREAD

**Issue by MlopsFunny** [bottlesdevs/Bottles#3154]
### Describe the bug

the app cannot find custom configuration files from the system.

### To Reproduce

1. Factory Reset
2. Install Bottles via discovery
3. Create new bottle
4. Custom enviroment
5. Attempt loading a custom config via the "Configuration" setting.

### Package

Flatpak from Flathub

### Distribution

SteamOS 3.4.11

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: plasma-steamos-oneshot
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.13.0-valve37-1-neptune
Disk:
    Total: 7778656256
    Free: 7778504704
RAM:
    MemTotal: 14.5GiB
    MemAvailable: 10.5GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
(1)(deck@steamdeck ~)$ flatpak run com.usebottles.bottles
14:53:35 (INFO) Bottles Started! 
14:53:40 (INFO) Performing Bottles checks… 
14:53:40 (INFO) Dxvks found:
         - dxvk-2.3
 
14:53:40 (INFO) Vkd3ds found:
         - vkd3d-proton-2.10
 
14:53:40 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.4
 
14:53:40 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
14:53:40 (INFO) Runners found:
         - soda-7.0-9
         - sys-wine-8.0.2
 
14:53:40 (ERROR) Config file not exists 
Traceback (most recent call last):
  File "/app/share/bottles/bottles/backend/models/config.py", line 183, in load
    raise FileNotFoundError("Config file not exists")
FileNotFoundError: Config file not exists
14:53:41 (INFO) Catalog dependencies loaded 
14:53:41 (INFO) Catalog components loaded 
14:53:41 (INFO) Catalog installers loaded
```

**Comment by TomChapple** [comment]
When I'm running the development build, I get a similar option. From inspection, it appears as though the filters for "YAML" and "All Files" are not present, meaning that no file is valid. You can see a screenshot of this below:

![No Filters](https://github.com/bottlesdevs/Bottles/assets/22762625/792a32bd-948f-4f05-8a8e-c26f10b026d0)

When debugging this build, I can see that the filters are indeed present when [`dialog.show()`](https://github.com/bottlesdevs/Bottles/blob/830b09aeee448e0c603b5d6100de0b11a83f76ee/bottles/frontend/views/new.py#L145) is called, so I am naively assuming this is an issue with Gtk.

The use of `Gtk.FileChooserNative` may be relevant here as [the class is deprecated as of 4.10](https://docs.gtk.org/gtk4/class.FileChooserNative.html) and it is recommended to use [`Gtk.FileDialog`](https://docs.gtk.org/gtk4/class.FileDialog.html) instead. Perhaps this section is in need of an update to the new API?

Lastly, I saw the MIME type for YAML files being specified as `application/x-yaml` even though [`application/yaml`](https://www.iana.org/assignments/media-types/application/yaml) is now a valid IANA media type. I can understand `application/x-yaml` being present for backwards compatibility, but maybe `application/yaml` needs to be included as an additional mime type.

This is all from someone who has spent a very short time starting up the app in `pdb` and then looking at some symptoms. As such, I'm sure I will be missing something important or placing too much importance on something else. If I get the chance, I'll see if I can replace the dialog with `Gtk.FileDialog` and see what happens.

**Comment by TomChapple** [comment]
Okay, initial tests using `Gtk.FileDialog` have been unsuccessful; I get the same issue where the filters are not listed even with this new API.

**Comment by TomChapple** [comment]
Well this show's my inexperience, the `Gtk.FileDialog` is only an option based on recent Gtk versions, so it is entirely possible that `Gtk.FileChooserNative` needs to be there for backwards compatibility.

I was able to use a `Gtk.FileChooserNative` in a small script cobbled from various tutorials and this project (seen below) and the filters appear and function as intended. I don't know if this is a side-effect of being run natively rather than in a Flatpak sandbox, but it definitely indicates there is more to this issue than simply "one side is messed up".

```python
#/usr/bin/env python3

import sys

import gi
gi.require_version("Gtk", "4.0")
from gi.repository import GLib, Gtk, Gio

class MyApplication(Gtk.Application):
    def __init__(self):
        super().__init__(application_id="com.example.MyGtkApplication")
        GLib.set_application_name('My Gtk Application')

    def do_activate(self):
        self.window = Gtk.ApplicationWindow(application=self, title="Hello World")
        self.window.present()
        self.box1 = Gtk.Box()
        self.window.set_child(self.box1)

        self.button = Gtk.Button(label="Hello")
        self.box1.append(self.button)

        self.button.connect('clicked', self._do_file_chooser_native)

    def _do_file_chooser_native(self, button):
        def set_path(_dialog, response: Gtk.ResponseType):
            if response == Gtk.ResponseType.ACCEPT:
                print("Accepted!")

        self.dialog = Gtk.FileChooserNative.new(
            title="Select a Configuration File",
            action=Gtk.FileChooserAction.OPEN,
            parent=self.window,
        )

        filter = Gtk.FileFilter()
        filter.set_name("YAML")
        filter.add_mime_type("application/x-yaml")
        self.dialog.add_filter(filter)

        filter = Gtk.FileFilter()
        filter.set_name("All Files")
        filter.add_pattern("*")
        self.dialog.add_filter(filter)

        self.dialog.set_modal(True)
        self.dialog.connect("response", set_path)
        self.dialog.show()

app = MyApplication()
exit_status = app.run(sys.argv)
sys.exit(exit_status)
```

**Comment by BrochachoTheBro** [comment]
Having the same issue. Is there a workaround until this is fixed?

**Comment by CartoonistDude** [comment]
I was also trying to use .yml files and found out this was an issue.
Is there a easy way to use a previous/older build until it gets fixed? The last version I used work great but that was a few months ago and still fairly new to understanding Linux.

**Comment by TomChapple** [comment]
I don't have any workarounds just yet, but perhaps [this page on the Flatpak Wiki](https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#downgrading) may help. For any information regarding Bottles, I would refer to [the page on FlatHub](https://flathub.org/apps/com.usebottles.bottles).

Regarding some investigation, I found that commenting [`add_yaml_filters`](https://github.com/bottlesdevs/Bottles/blob/f9c19ae7cd2c830ee085aad30c8076207331a7e0/bottles/frontend/views/new.py#L170) when creating that `FileChooserNative` will result in the All Files filter being the default and allowing for the YAML files to be chosen without error. I'm not sure why removing the YAML filter causes this to work and I'm hesitant to suggest this as a change due to the pretty bad UX it introduces, but I can do some further experimentation to see if I can get something consistent in the mean-time.

**Comment by eskay993** [comment]
Thanks for looking into this. Just to report, rolling back to an earlier version worked as a temp workaround on Nobara 38 using KDE. I had to roll back to Bottles v51.5 (later versions all had the same issue). This is the command to rollback for anyone interested:

```
flatpak update --commit=209f11158cdb135bf54178da6bba6a6769e1b261ef4844d9d08fa306a90e82ec com.usebottles.bottles
```

**Comment by MoodySshuffle** [comment]
Wanted to confirm that the issue still persists on version 51.10.

**Comment by TomChapple** [comment]
> Thanks for looking into this. Just to report, rolling back to an earlier version worked as a temp workaround on Nobara 38 using KDE. I had to roll back to Bottles v51.5 (later versions all had the same issue). This is the command to rollback for anyone interested:
> 
> ```
> flatpak update --commit=209f11158cdb135bf54178da6bba6a6769e1b261ef4844d9d08fa306a90e82ec com.usebottles.bottles
> ```

Thanks for the command! I can confirm that using this command works for me also, but there are still strange symptoms. That is, there is only one filter—"YAML document"—instead of the two that are defined in the code base—"YAML" and "All Files".

So whilst this is a temporary workaround, it's tough to say that this is simply a regression issue as it looks like the same problem occurs in 51.5 as well. It just so happens to line up in a way that doesn't remove the ability to choose YAML files.

**Comment by MoodySshuffle** [comment]
> > Thanks for looking into this. Just to report, rolling back to an earlier version worked as a temp workaround on Nobara 38 using KDE. I had to roll back to Bottles v51.5 (later versions all had the same issue). This is the command to rollback for anyone interested:
> > ```
> > flatpak update --commit=209f11158cdb135bf54178da6bba6a6769e1b261ef4844d9d08fa306a90e82ec com.usebottles.bottles
> > ```
> 
> Thanks for the command! I can confirm that using this command works for me also, but there are still strange symptoms. That is, there is only one filter—"YAML document"—instead of the two that are defined in the code base—"YAML" and "All Files".
> 
> So whilst this is a temporary workaround, it's tough to say that this is simply a regression issue as it looks like the same problem occurs in 51.5 as well. It just so happens to line up in a way that doesn't remove the ability to choose YAML files.

How did you get it to work? When I go to use the command, it works until it hits com.usebottles.com, at which point it errors out saying it can't make commits without root permissions. Looking that up, I couldn't find much solution since, very understandably and agreeably, no one wants to guide someone into a very dangerous prospect like that. 

Not much I tried to get it to work, but I know downloading and installing the Flathub copy rather than the Discover copy did not help.

**Comment by TomChapple** [comment]
@MoodySshuffle I ended up using `sudo` for mine to install it with the commit. I'm personally comfortable with using that command, but hesitance against executing root-level commands makes a lot of sense. I'm not sure there's much I can do to convince you use that command, especially given the Gnome Platform version Bottles 51.5 uses is now end of life.

**Comment by TomChapple** [comment]
Okay, quick update: I went back a few versions and can confirm that this symptoms started in version 51.0. Versions 50.1 and 50.2 showed the filters correctly in the "Select a Configuration File" menu, but 51.0 onward shows either one of them or neither.

Doing a comparison between versions 50.2 and 51.10 around the function `__choose_env_recipe` in `bottles/frontend/views/new.py`, shows a diff _similar_ to the following:

```diff
-    def choose_env_recipe(self, *_args):
+    def __choose_env_recipe(self, *_args) -> None:
+        """
+        Opens a file chooser dialog to select the configuration file
+        in yaml format.
+        """
-        def set_path(_dialog, response):
+        def set_path(_dialog, response: Gtk.ResponseType):
             if response == Gtk.ResponseType.ACCEPT:
+                self.btn_choose_env_reset.set_visible(True)
                 self.env_recipe_path = dialog.get_file().get_path()
+                self.label_choose_env.set_label(dialog.get_file().get_basename())
+                self.label_choose_env.set_ellipsize(Pango.EllipsizeMode.MIDDLE)
 
         dialog = Gtk.FileChooserNative.new(
-            title=_("Select a Recipe"),
+            title=_("Select a Configuration File"),
             action=Gtk.FileChooserAction.OPEN,
             parent=self.window,
         )
```

As can be seen, the structure and protocol for defining this dialog has not changed substantially (especially given that the filter definitions are not listed as being changed). As such, this would appear to me as either a global (or at least a larger scope) change in the Gtk configuration or some weird inconsistency in functionality in versions of Gtk deployed in the Gnome platform.

**Comment by TomChapple** [comment]
Okay, looks I was a little hasty. The definition of the YAML filter (defined in `bottles/frontend/utils/filters.py`) was changed between 50.2 and 51.10 in the following manner:

```diff
 def add_yaml_filters(dialog):
     filter = Gtk.FileFilter()
     filter.set_name("YAML")
-    # TODO: Create yaml media type https://www.ietf.org/archive/id/draft-ietf-httpapi-yaml-mediatypes-00.html#name-media-type-application-yaml
-    filter.add_pattern("*.yml")
-    filter.add_pattern("*.yaml")
+    filter.add_mime_type("application/x-yaml")

     dialog.add_filter(filter)
```

Specifically, the `add_pattern` calls were replaced with `add_mime_type`. Doing this same change in version 50.2 results in the same symptoms as experienced in 51.5 and using `add_pattern` in 51.10 resolves the issue entirely. It looks like the issue may be due to this mime type method in some regard, whether it's specific to `application/x-yaml` or not, I'm not sure.

**Comment by TomChapple** [comment]
The linked pull request above aims to address the issue described here, but I have only tested it on my personal Kubuntu machine; I don't know if this resolves the issues seen on the Steam Deck or if it has adverse side-effects on Linux distributions. If anyone has the ability to checkout that branch and verify it functions (or continues to function), that would be greatly appreciated.

**Comment by eskay993** [comment]
Thanks for this! I tested it on my desktop running Noabra 39, which was experiecne the issue before, and it working fine now! I'll have some time to test it on my Steam Deck this weekend and report on the PR thread.

I don't have a Linux distro where I wasn't experiencing the issue before to test thast  (bot Noabra and Fedora for me

**Comment by ndegug** [comment]
> Thanks for looking into this. Just to report, rolling back to an earlier version worked as a temp workaround on Nobara 38 using KDE. I had to roll back to Bottles v51.5 (later versions all had the same issue). This is the command to rollback for anyone interested:
> 
> ```
> flatpak update --commit=209f11158cdb135bf54178da6bba6a6769e1b261ef4844d9d08fa306a90e82ec com.usebottles.bottles
> ```

Hi, I'm getting 404'ed every time I try this, is there any way to fix that?

**Comment by dCo3lh0** [comment]
i'm having the same issue, but now i cant downgrade till 51.5 i think you guys said it doesn't display this issue, it goes back only to 51.9

**Comment by TomChapple** [comment]
The latest development build of Bottles has a fix in place. If you're comfortable doing so, you can build Bottles by following the "Building" instructions on the repository's home. That's probably the most reliable method of getting this fix installed, as awkward as it is.

If you can find a way to install version 50.2, that's the most recent stable version doesn't experience this issue. However, I haven't found a command to revert to that version (I cannot figure out where the `--commit` hash comes from).

**Comment by ndegug** [comment]
> The latest development build of Bottles has a fix in place. If you're comfortable doing so, you can build Bottles by following the "Building" instructions on the repository's home. That's probably the most reliable method of getting this fix installed, as awkward as it is.
> 
> If you can find a way to install version 50.2, that's the most recent stable version doesn't experience this issue. However, I haven't found a command to revert to that version (I cannot figure out where the `--commit` hash comes from).

Will there be an update downloadable from the Discovery Store soon? I'm trying to get this working on the Steam Deck and it seems like every time I fix one problem, there's a new issue.

**Comment by TomChapple** [comment]
For those following, the updates as of 51.12 (including 51.13 as of commenting) now have the change that resolves this issue in place. This is available on FlatHub for download, so feel free to download it and verify that it now works as intended.

**Comment by stefan-girlich** [comment]
Experiencing this in 51.18. Also see #3657

**Comment by TomChapple** [comment]
So I don't experience the same issue as above, but I do notice a discrepancy between my main PC and the Steam Deck. On my main PC, I can see two options: "YAML" and "All documents". Whereas on the Steam Deck I can only see "YAML documents". Both instances were using Bottles version 51.21 downloaded as Flatpaks.

Only one option being available on the Steam Deck sounds reminiscent of the original issue where only one or none of the file type picker options worked.

Looking for code changes surrounding filters since 51.13 (where the initial issue was discovered), I notice that a new file has been added in the past couple of months: `bottles/frontend/views/new_bottle_dialog.py`. This seems to correspond with new UI, with the "Import configuration" option linking to a function called [`__choose_env_recipe`](https://github.com/bottlesdevs/Bottles/blob/51.21/bottles/frontend/views/new_bottle_dialog.py#L145). Inside this function, there is code to define this filter... using the old method that was shown to be inconsistent in this same issue.

My theory is that the inconsistency showing to be the root cause continues to be present, requiring the use of the old method of specifying each MIME type by hand. During the move to new UI elements, this fact was missed and was reintroduced. Again, this is a theory as I don't actively work on Bottles. If any active maintainers could provide comment on this, that would be very insightful!

I can see if I can make a fork of this to validate if using the previous fix resolves this issue again in the mean time.

**Comment by TomChapple** [comment]
Well, I have bad news: the development environment isn't cooperating on my end (neither on my main PC nor my Steam Deck). I have put together a pull request—#3828—that seemingly addresses the issue, but I have not been able to test it yet. If anyone familiar with the current development environment can validate this functionality, I would greatly appreciate it!

Otherwise, I will be investigating why I cannot get this development environment set up as expected.

**Comment by TomChapple** [comment]
Okay, a little update: I was able to test this pull request on my Steam Deck, and it worked! Turns out when you submit a pull request, it generates a flatpak file you can install locally, so I just used that.

The file has expired now, unfortunately, but hopefully this will be sufficient enough for the pull request to be merged. If anyone who can make a development build sees this on another OS, any additional testing that can be recorded on that PR would be greatly appreciated.
