### ISSUE TITLE
[Request]: Support Wezterm and Alacritty terminals

### ISSUE THREAD

**Issue by OmegaRogue** [bottlesdevs/Bottles#3168]
### Tell us the problem or your need

I use Wezterm as a terminal, and have alacritty as a fallback. Neither of those are in the list of supported terminals
https://github.com/bottlesdevs/Bottles/blob/830b09aeee448e0c603b5d6100de0b11a83f76ee/bottles/backend/utils/terminal.py#L38-L55

### Describe the solution you'd like

```
['wezterm', '-e %s'],
['alacritty', '--hold -e %s'],
```

**Comment by orowith2os** [comment]
We've only been supporting Flatpak for a while now, so that list is unnecessary, as we only support easyterm (it being shipped by us). Until a new spec exists for us to spawn a terminal on the host (which will be a while), supporting anything other than easyterm is not planned.

We'll remove that list in the meantime.

**Comment by OmegaRogue** [comment]
Where can I find easyterm? (assuming it works outside of flatpak)

**Comment by orowith2os** [comment]
In our Flatpak package.

**Comment by obsidianical** [comment]
what about just making it possible to use your own terminal command?

**Comment by orowith2os** [comment]
If you want to see any changes here, make the upstream xdg terminal preference spec move some. Nothing will change otherwise.

**Comment by obsidianical** [comment]
"if you want *me* to improve my software, change the spec, because i dont give a shit about you, my users!" 

...seriously?

**Comment by orowith2os** [comment]
Yes. Seriously.
