### ISSUE TITLE
[Bug]: Doesn't open with Xfce4 terminal: 'Unknown option: "cmd"'

### ISSUE THREAD

**Issue by SeongGino** [bottlesdevs/Bottles#3193]
### Describe the bug

Trying to open a command line in Bottles with `xfce4-terminal` installed will cause that error to happen.

Looks like the return of #1097

### To Reproduce

1. Open Bottles in a terminal
2. Open up a bottle, go to Tools -> Command Line
3. Observe the error.

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: false
Version: 51.9-f9c19ae7
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/share/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.8-273-tkg-linux-tkg-pds
Disk:
    Total: 96634667008
    Free: 7796563968
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 7.3GiB
Bottles_envs: null
Tools and Libraries:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.38'
    icoextract: true
    pefile: true
    orjson: true
    markdown: true
    ImageMagick: true
    FVS: true
    xdpyinfo: true
```

### Troubleshooting Logs

```shell
21:28:26 (INFO) Using Wine Command Line -- launch_terminal 
21:28:26 (INFO) Command: xfce4-terminal -e 'sh -c '/home/seong/.local/share/bottles/runners/wine-ge-proton8-24/bin/wine64 cmd'' 
xfce4-terminal: Unknown option "cmd"
```

### Additional context

Applies to native AUR `bottles-git` package, not the flatpak; debugging information is accurate to the native version being run.

**Comment by orowith2os** [comment]
This is not a Bottles issue, and we don't officially support non-Flatpak
packages of Bottles.

**Comment by pato-pan** [comment]
The error is reproducible if you run the command directly from the terminal

```
21:28:26 (INFO) Using Wine Command Line -- launch_terminal 
21:28:26 (INFO) Command: xfce4-terminal -e 'sh -c '/home/duck/.local/share/bottles/runners/wine-ge-proton8-25/bin/wine64 cmd''
xfce4-terminal: Unknown option "cmd"
```

When I replace the last single quotes for double quotes, it works as expected (beware, this uses your system prefix instead of a bottles prefix)
```
xfce4-terminal -e 'sh -c '/home/duck/.local/share/bottles/runners/wine-ge-proton8-25/bin/wine64 cmd''
```

Hopefully this is easy to implement. Even if it's not officially supported, it would be nice to have this fix as long as it doesn't break the flatpak version or causes any bugs. I have yet to test this

**Comment by pato-pan** [comment]
@mirkobrombin I see what you are saying, and looking at the code it makes sense to think it should work. Now, the only thing left to understand is....
![Screenshot_2024-05-19_18-35-20](https://github.com/bottlesdevs/Bottles/assets/131620424/6c1876b8-7edf-480a-b381-db37c7317d58)
Why does the program reflect something different!?!? Single quotes instead of double quotes! The quotes starting at sh instead of at -e. I don't get it, probably some kind of bash translation thing. Maybe if I revisit this I'll understand what's happening, make a pull request and fix this, but I can't promise I'll do that any time soon. Thank you for showing me that file to point me in the right direction though

**Comment by mirkobrombin** [comment]
I am not really the maintainer of that package. The maintainer is lotation

**Comment by owopeachy** [comment]
> Why does the program reflect something different!?!? Single quotes instead of double quotes! The quotes starting at sh instead of at -e. I don't get it, probably some kind of bash translation thing.

Line 106 on the linked code is why, for xfce it adds single quotes for whatever reason. Thankfully its easy to tweak the py file to fix this :)

**Comment by pato-pan** [comment]
> > Line 106 on the linked code is why, for xfce it adds single quotes for whatever reason. Thankfully its easy to tweak the py file to fix this :)

Do you know if this is a problem with other desktop environments based on xorg? I don't have a reliable way to test this.
