### ISSUE TITLE
[Request]:  please add APPIMAGE

### ISSUE THREAD

**Issue by fralujo** [bottlesdevs/Bottles#3208]
### Tell us the problem or your need

there is no APPIMAGE build

### Describe the solution you'd like

please add APPIMAGE build

**Comment by Palace4Software** [comment]
I also would enjoy an AppImage.

**Comment by orowith2os** [comment]
No.

**Comment by ivan-hc** [comment]
Hi @orowith2os , do you remember me? I am that developer[ looking for help in creating an AppImage](https://github.com/bottlesdevs/Bottles/issues/2947). I did it:

- https://github.com/ivan-hc/Bottles-appimage
- https://github.com/ivan-hc/Bottles-appimage/releases/tag/continuous

as souces I've compiled everything from AUR and then implemented all the needed packages on a Debian base. My AppImage is about 160MB only and works without having WINE installed... Soda and other runners are enough. It works great for me... at least with 64bits programs.

In reality I was looking for a 32bit version of the Soda runner, because I have some old games to play with and I'd prefer not to include 32bit libraries and WINE, not in my package (the Flatpak is already too much bloated for me... or not just for me) and not on the host. Suggestion? Are there some Soda/Coffee 32bit runners I can use with my Appimage? Thanks in advance.

**Comment by orowith2os** [comment]
Wine should already require 32-bit libs unless it's built with wow64 support, even on the 64-bit version. So you'd need to bundle them anyways, but you don't need a 32-bit-specific build of Wine for that.

In any case, expect to be solving any problems yourself. This is still unsupported territory.

**Comment by ivan-hc** [comment]
@orowith2os really I have also an appimage of WINE. If I move it away from a $PATH, Bottles does not sees it, while it recognizes it if in $PATH. However, I'm still using Bottles AppImage for 64bit games and WINE for 32bit ones. I think that Bottles does not recognizes the 32bit version because the WINE Appimage is one file I named "wine", in $PATH (as a symlink, at least), but I'm sure that if I had WINE installed system wide, 32bit games should work well under Bottles.

In my first propotype, the Archimage (Arch Linux container into an AppImage) I had full wine and 32bit libraries (the archive was about 600-800 MB) and 32bit games were working, but being it a container into an appImage, I was unable to use hardware accelleration for 64bit programs.

That said, this new approach I've used to build the AppImage package works without WINE built into the archive.

> In any case, expect to be solving any problems yourself. This is still unsupported territory.

that's right, I'm the developer of the AppImage, mine is the responsability if it will not work, not yours. Now, the important thing is that I managed to build an unofficial version that works. Now, the important thing is that I managed to build an unofficial AppImage version that works for me, so I can finally avoid installing stuff I don't need but needed by Flatpak to just use Bottles.

I would like to thank the maintainer of the AUR package, without whom this work of mine would not have been possible.

See you.

**Comment by Palace4Software** [comment]
> Hi @orowith2os , do you remember me? I am that developer[ looking for help in creating an AppImage](https://github.com/bottlesdevs/Bottles/issues/2947). I did it:
> 
> * https://github.com/ivan-hc/Bottles-appimage
> * https://github.com/ivan-hc/Bottles-appimage/releases/tag/continuous
> 
> as souces I've compiled everything from AUR and then implemented all the needed packages on a Debian base. My AppImage is about 160MB only and works without having WINE installed. Soda and other runners are enough. It works great for me... at least with 64bits programs.
> 
> In reality I was looking for a 32bit version of the Soda runner, because I have some old games to play with and I'd prefer not to include 32bit libraries and WINE, not in my package (the Flatpak is already too much bloated for me... or not just for me) and not on the host. Suggestion? Are there some Soda/Coffee 32bit runners I can use with my Appimage? Thanks in advance.

Thank you! That's exactly what I wanted and needed.
