### ISSUE TITLE
[Request] Change the settings for multiple bottles at once

### ISSUE THREAD

**Issue by Toadfield** [bottlesdevs/Bottles#321]
**Is your feature request related to a problem? Please describe.**
I have many bottles,but I want to test another msstyle wine theme and change the dxvk version,the problem is that I would have to change that for every prefix seperately.

**Describe the solution you'd like**
That I can apply one setting to every prefix.

**Comment by mirkobrombin** [comment]
I don't like this idea as each bottle has its own dependencies and specific settings. Applying the same configuration to multiple bottles with a different base can compromise their functionality.

For what I know if there is a function, the user will use it and for this reason I cannot integrate a function that can damage 99% of users' bottles.Furthermore Bottles V4 will not allow this integration due to the dependency system which keeps track of every modification and software installed to ensure the correct functioning of the installers.

**Comment by Toadfield** [comment]
What about being able to just change the winecfg options for all prefixes at once?
(or just make the setting hard to activate,put something like "could damage your bottle,activate at your own risk!" in the title of the setting)

**Comment by mirkobrombin** [comment]
> What about being able to just change the winecfg options for all prefixes at once?
> (or just make the setting hard to activate,put something like "could damage your bottle,activate at your own risk!" in the title of the setting)

Because in Bottles V4 all winecfg settings are integrated into Bottles GUI and these also need to be tracked by the dependency manager

**Comment by Toadfield** [comment]
Then what about my second approach (so that you make it hard to enable that setting)?

**Comment by mirkobrombin** [comment]
> Then what about my second approach (so that you make it hard to enable that setting)?

I don't know, I have to think about it. Definitely not in Bottles 3.2 but after Bottles 4.0.

**Comment by mirkobrombin** [comment]
Returning to this. This actually is an unsafe bad ux approach. Each bottle should be configured for its scope. To "replicate" configurations, just use a custom environment recipe or duplicate the bottle.
