### ISSUE TITLE
Can't load the executable libraries

### ISSUE THREAD

**Issue by hardBSDk** [bottlesdevs/Bottles#3213]
Before the 51.10 update my games were running normally, after the 51.10 update they can't read their libraries anymore.

- The terminal log when loading a game:

```
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
0088:err:hid:udev_bus_init UDEV monitor creation failed
00d8:err:module:import_dll Library FC3.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\bf1dd8ff\\farcry3.exe") not found
00d8:err:module:LdrInitializeThunk Importing dlls for L"Z:\\run\\user\\1000\\doc\\bf1dd8ff\\farcry3.exe" failed, status c0000135
```

I tried to add the games folder on Bottles using Flatseal, don't work.

**Comment by koplo199** [comment]
Well, this time I'm quite sure the issue stems from the [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal). Can you confirm you added your game through the "Add shortcut" button?

If so, please delete the shortcut, run Bottles with the following command : `flatpak run --no-talk-name="org.freedesktop.portal.FileChooser" com.usebottles.bottles`, and re-add it[^1]. The right path should be used this time.

The good news is that it's a one time fix (doesn't need to be done every time), the bad news is, as you guessed it, it's not a Bottles bug and thus you'll have to wait for your distribution to ship a fixed `xdg-desktop-portal` package.

[^1]: And you're in luck, because as you already [know](https://github.com/bottlesdevs/Bottles/issues/3212) there's another bug outside of our control causing the `exe` not to show right away, so use the newly added "All files" option to be able to add it.

**Comment by hardBSDk** [comment]
@koplo199 Yes, I used the "Add shortcuts" button, I did what you said, don't work, I'm using the 51.10 version and there's no "All files" file type on the file picker, still "Windows Installer package".

I'm using PopOS 22.04, I updated the system yesterday.

The log:

```
~> flatpak run --no-talk-name="org.freedesktop.portal.FileChooser" com.usebottles.bottles                                                          12/24/23 19:31:06 PM

(process:2): Gtk-WARNING **: 19:31:06.501: Locale not supported by C library.
        Using the fallback 'C' locale.
19:31:07 (INFO) Bottles Started! 

(bottles:2): Gtk-WARNING **: 19:31:07.148: AdwViewSwitcher 0x5cc8a8a96a90 (viewswitcher) reported min height -6, but sizes must be >= 0
19:31:11 (INFO) Performing Bottles checks… 
19:31:11 (INFO) Dxvks found:
         - dxvk-2.3
 
19:31:11 (INFO) Vkd3ds found:
         - vkd3d-proton-2.10
 
19:31:11 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.4
 
19:31:11 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
19:31:11 (INFO) Runners found:
         - wine-ge-proton8-25
         - sys-wine-8.0.2
 
19:31:11 (INFO) Temp directory cleaned successfully! 
19:31:11 (INFO) Bottles found:
         - Agony
 
19:31:12 (INFO) Catalog dependencies loaded 
19:31:12 (INFO) Catalog components loaded 
19:31:13 (INFO) Catalog installers loaded 
19:31:20 (INFO) Setting Key sync=fsync for bottle Agony… 
19:31:20 (INFO) There is no running wineserver. 
19:32:02 (INFO) Setting Key 25fd6796-4524-4be7-baaa-059652bc33cf={'executable': 'farcry3.exe', 'name': 'farcry3', 'path': '/run/user/1000/doc/bf1dd8ff/farcry3.exe', 'id': '25fd6796-4524-4be7-baaa-059652bc33cf', 'folder': '/run/user/1000/doc/bf1dd8ff'} for bottle Agony… 
19:32:10 (INFO) Launching an executable… 
19:32:10 (INFO) Using EasyAntiCheat runtime 
19:32:10 (INFO) Using BattlEye runtime 
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
0088:err:hid:udev_bus_init UDEV monitor creation failed
00d8:err:module:import_dll Library FC3.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\bf1dd8ff\\farcry3.exe") not found
00d8:err:module:LdrInitializeThunk Importing dlls for L"Z:\\run\\user\\1000\\doc\\bf1dd8ff\\farcry3.exe" failed, status c0000135
19:32:20 (INFO) Launching an executable… 
19:32:20 (INFO) Command: easyterm.py -d -p "#00ffff #2b2d2e" -c 'bash -c '"'"'/home/hatred_45/.var/app/com.usebottles.bottles/data/bottles/runners/wine-ge-proton8-25/bin/wine64 /run/user/1000/doc/bf1dd8ff/farcry3.exe'"'"'' 

(easyterm.py:183): Gtk-WARNING **: 19:32:20.722: Locale not supported by C library.
        Using the fallback 'C' locale.

(easyterm.py:183): VTE-WARNING **: 19:32:20.794: (../src/vtepty.cc:810):void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
```

**Comment by fredinwheel** [comment]
Same problem here, same distribution. Everything used to work before I updated today. While I usually don't notice when these things happen, the problem here was obvious since in the morning before I ran "flatpak update", I could execute all programs.

Distro: PopOS 22.04
Runner: Soda 8.0-2

Now I get the same error as @hardBSDk (with a different dll import failure): 

```
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
00e8:err:module:import_dll Library UnityPlayer.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\#####") not found
00e8:err:module:LdrInitializeThunk Importing dlls for L"Z:\\run\\user\\1000\\doc\\#####" failed, status c0000135
```

Sadly, the fix you've suggested also hasn't worked for me.

**Comment by hardBSDk** [comment]
@fredinwheel Interesting, the Soda runner also gives this error, I tought it was Wine GE specific.

If it was an upstream change from FreeDesktop, PopOS shouldn't have this problem because the versions are locked.

**Comment by koplo199** [comment]
> @koplo199 Yes, I used the "Add shortcuts" button

Thanks for confirming.

> I did what you said, don't work, I'm using the 51.10 version and there's no "All files" file type on the file picker, still "Windows Installer package".

Bottles 51.10 precisely is the version with an "All files" options for the shortcut, please double check.

> The log:
> ...
> 19:32:02 (INFO) Setting Key 25fd6796-4524-4be7-baaa-059652bc33cf={'executable': 'farcry3.exe', 'name': 'farcry3', 'path': '/run/user/1000/doc/bf1dd8ff/farcry3.exe', 'id': '25fd6796-4524-4be7-baaa-059652bc33cf', 'folder': '/run/user/1000/doc/bf1dd8ff'} for bottle Agony… 

I should have been more clear, but I meant recreating the shortcut using the "real" path of the executable, the one inside the sandbox. It should begin with something like `/home/YOUR_USERNAME/.var/app/com.usebottles.bottles/data/bottles/bottles/YOUR_BOTTLE_NAME/drive_c/...`. Anything begining with `/run/user/1000/doc` is the root cause of the issue, and won't work.

**Comment by hardBSDk** [comment]
@koplo199 Sure, because I'm running these executables out of the Bottles sandbox at `~/Documents/Tijolo`, I will move them to the bottle files and test.

Yes, it's 51.10

```
~> flatpak info com.usebottles.bottles                                                                                                             12/24/23 20:10:45 PM

Bottles - Run Windows Software

          ID: com.usebottles.bottles
         Ref: app/com.usebottles.bottles/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 51.10
     License: GPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 481.9?MB
     Runtime: org.gnome.Platform/x86_64/45
         Sdk: org.gnome.Sdk/x86_64/45

      Commit: 34fd84393ff5717222995783ae052c4da78ab0e15bfeb9649b1bdf3f72592235
      Parent: ffe7d2673449aaf63d08da8e493628b1564b7bf7b084f05787fb9243d8b3633f
     Subject: Update manifests (1f34ad81)
        Date: 2023-12-23 22:38:50 +0000
```

**Comment by hardBSDk** [comment]
@koplo199 @fredinwheel Moving the game to the bottle files fixed the problem! basically it's a sandbox problem where Bottles can't read the user files at `/home/user-name` (it was possible in the previous versions, maybe something enforced a more secure policy).

As you can't access the Flatpak folder at `/home/user-name/.var` from the file picker, you need to open your Nautilus or Dolphin file manager and bookmark the `drive_c` folder of your bottle, it will appear inside of `xdg-desktop-portal` and you can add your game executable without a Flatseal rule.

- Nautilus - Bookmark the folder.
- Dolphin - Add the folder to "Places".

**Comment by hardBSDk** [comment]
@koplo199 Bottles is not respecting the Flatseal rules to give permission for directories.

**Comment by koplo199** [comment]
> @koplo199 Bottles is not respecting the Flatseal rules to give permission for directories.

Bottles doesn't decide nor is even aware of permission for specific directories, it simply doesn't have this power (it would be a serious security issue otherwise). But yes, it looks like something is wrong with permissions, maybe reseting them through Flatseal and re-apply them will fix the issue. Or using the command line, `flatpak override com.usebottles.bottles --filesystem=~/Documents/Tijolo` in your case.

But permissions aren't the only appearing issue, judging by the output of the command it also completly ignored the `--no-talk-name="org.freedesktop.portal.FileChooser"` instruction and still gave you a `/run/user/1000/doc` path. Nice.

I don't know what's happening with Ubuntu related distribution at the moment, but the whole situation is a serious mess.

**Comment by hardBSDk** [comment]
@koplo199 Investigating more the issue, it probably disabled all permissions, Flatseal show that the PulseAudio permission is enabled but in fact it's disabled (no sound in the game).

Flatpak is not applying the permission without root, I think it's the issue, Flatseal start as rootless.

Maybe it's a Polkit problem.

**Comment by hardBSDk** [comment]
@koplo199 The problem is more severe, it's ignoring permissions.

I tried to run `flatpak override com.usebottles.bottles --socket=pulseaudio` with root, it gave success but don't work (still no sound in the game.

**Comment by koplo199** [comment]
I don't remember sudo being even necessary for setting an override, try adding `--user` instead (`flatpak override --user ...`).

But honestly I'm shooting in the dark, and the only thing that is clear is that it's not a Bottles issue. With the additional informations you provided, the hypothesis of a `xdg-desktop-portal` issue also doesn't fit, it wouldn't affect sound at all.

**Comment by hardBSDk** [comment]
@koplo199 I ran `flatpak override --user` but the sound of the game still don't work.

**Comment by fredinwheel** [comment]
> @koplo199 @fredinwheel Moving the game to the bottle files fixed the problem! basically it's a sandbox problem where Bottles can't read the user files at `/home/user-name` (it was possible in the previous versions, maybe something enforced a more secure policy).

Thanks, I just copied them over to the bottles directory and everything is working again. 

Though, I really wish Bottles functionality would be restored so that it wouldn't require it. This is an admittedly small extra step but I fear that a lot of people who may need this solution won't even come across your solution here. Many will simply assume that Bottles doesn't work with their executable.

Sound works for me in the games that are copied to the directory. @hardBSDk , your sound issues are related to @koplo199 's recommendation with permissions right?

**Comment by hardBSDk** [comment]
@fredinwheel Basically it disable all permissions and only access the bottle files, that's it, it can render windows but nothing extra like play sound because the PulseAudio IPC is blocked.

**Comment by fredinwheel** [comment]
> I don't know what's happening with Ubuntu related distribution at the moment, but the whole situation is a serious mess.

@koplo199  sometimes that really is the problem but I feel like it's also often overestimated.

I've since been able reproduce the problem in a variety of Linux distributions (through kvm, if that's relevant):

1. PopOS 22.04 (Fresh)
2. Kubuntu 22.04.3
3. Manjaro XFCE 23.1.1-231223
4. Fedora Silverblue 39 1.5

Settings were all the same:

- Bottles installed through Flathub
- Soda 8.0-2 as the runner

At this point, I'd argue that we can safely presume that all Linux distribution families are affected to some degree.

**Comment by koplo199** [comment]
> I've since been able to reproduce the problem in a variety of Linux distributions (through kvm, if that's relevant)
> ...
> At this point, I'd argue that we can safely presume all Linux distribution families being affected to some degree.

And I haven't been able to reproduce on any distribution. But you're right that I was mistaken thinking a particular distribution was the source of the issue, because it is not: it is particular users.

Let's take #3216 for example, it's 100% caused by a shitty frontend for flatpak that updated Bottles without updating the GNOME runtime (`org.gnome.Platform`). And depending on how disastrous that software is, it may or may not be fixed by a simple `flatpak update`. But hey no problem, because it's not him that will waste his time investigating that non-issue.

So I wish you luck in resolving your breakages, because as it has been established since the second [comment](https://github.com/bottlesdevs/Bottles/issues/3213#issuecomment-1868590904) it's not a Bottles 51.10 bug and, as such, I won't help more than I already did on that particlar issue which should be closed.

**Comment by fredinwheel** [comment]
@hardBSDk I changed the executable and voila stuff works once more. Sadly, I must have misinterpreted some coincidence there. Perhaps you may benefit from doing a general clean-up and re-install. I've heard people using flatsweep or warehouse for this purpose.

@koplo199 I'm not sure if you're enjoying yourself much here. Sorry to have added to your frustration, would recommend a breather if you're going through burnout.

**Comment by hardBSDk** [comment]
@koplo199 About the GNOME runtime version mismatch, I tested with 44 and 45, same problem in both.

I suggest a report to Flatpak upstream.

**Comment by hardBSDk** [comment]
@koplo199 @fredinwheel I sent this issue to Flatpak upstream.

https://github.com/flatpak/flatpak/issues/5639
