### ISSUE TITLE
[Request]: Roblox Support

### ISSUE THREAD

**Issue by ItsJustTee** [bottlesdevs/Bottles#3323]
### Tell us the problem or your need

I am a brand new Linux user and now on Day 2 of using Linux. Sadly Grapejuice and Vinegar have both been abandoned due to issues and I was actively looking for a way to play Roblox on Linux.

### Describe the solution you'd like

A simple, preset-written way to run and play Roblox on my Linux Mint installation

### Other solutions?

I have tried both Grapejuice and Vinegar but both were rendered obsolete and un-usable.

**Comment by AbdiAbdiAbdi** [comment]
Roblox officially disabled support for wine (vinegar and grapejuice are also running on wine) so there's no way to play Roblox on Linux. Only dual boot and emulators will work. 
I'd recommend dual booting, it's very easy to do using Gparted.

**Comment by Welved** [comment]
Doesn't roblox exclusively run on the web browser? You could try that/

**Comment by ItsJustTee** [comment]
> Doesn't roblox exclusively run on the web browser? You could try that.

Unsure if that works. Would you be able to show me how?

**Comment by kkrriisssshh** [comment]
> > Doesn't roblox exclusively run on the web browser? You could try that.
> 
> Unsure if that works. Would you be able to show me how?

it isn't possible, i've tried everything since roblox announced they stopped wine support, from wine and bottles to waydroid and my only option was to dualboot which made me stop playing the game entirely, now roblox developers did say that the ban may get removed someday but we dont have any dates so yea, pretty sad.

**Comment by kkrriisssshh** [comment]
> > > Doesn't roblox exclusively run on the web browser? You could try that.
> > 
> > 
> > Unsure if that works. Would you be able to show me how?
> 
> it isn't possible, i've tried everything since roblox announced they stopped wine support, from wine and bottles to waydroid and my only option was to dualboot which made me stop playing the game entirely, now roblox developers did say that the ban may get removed someday but we dont have any dates so yea, pretty sad.

i'd like to add something for people wondering why it wouldn't work:
- roblox blocks vms, when you try to launch it a popup saying "roblox does not support VMs" pops up
- wine/proton no longer works as Byfron (roblox's new anti cheat) stopped supporting it (by entirely disabling it when wine is detected)
- waydroid/any android emulator will usually entirely not work or be so incredibly slow that its unplayable because all android emulators use x86 images rather than arm images which is what the roblox android apk use, theoretically you can make this work with libhoudini but i've tried it and it is really useless unless its a simple app

now there is POSSIBLY a way to overcome the vm detection by using a DMA controller but thats just cheating :( hope one day they allow wine or update their stupid anticheat

**Comment by Welved** [comment]
> > Doesn't roblox exclusively run on the web browser? You could try that.
> 
> Unsure if that works. Would you be able to show me how?

Huh. Looks like roblox moved everything to their own standalone applications, the last time I checked; I was able to run the individual games in the browser.

**Comment by Welved** [comment]
> > Doesn't roblox exclusively run on the web browser? You could try that.
> 
> Unsure if that works. Would you be able to show me how?

For me, If I have a craving for a game that doesn't run on wine; I just spin up my windows 10 I have on a external SSD. There is a way to install Windows on a external medium and boot off USB.

**Comment by shawny43** [comment]
Roblox cannot be run on Linux because of Hyperion Anti-cheat software they bought. And yes they bring back again the software and broke the linux support. I guess they forgot there are Flatpak that could solve their problem for native support but hey, you can suggest roblox to support has well the linux native by publishing these into flatpak without hassle.

**Comment by Welved** [comment]
I don't care about roblox, I literally don't understand the appeal of it.

**Comment by mirkobrombin** [comment]
Wrong repo, use the programs repo.

**Comment by iqv124-normalperson2410** [comment]
some users on linux used wine to modify the client, so they stopped support for it entirely.
