### ISSUE TITLE
[Request] Working env directory. Wine's defaulting inner directories - problem

### ISSUE THREAD

**Issue by VProfirov** [bottlesdevs/Bottles#397]
Good day,
First I would like to express my sincere admiration for your project - very well done, so far!

Second, I have not found in the GUI menu/settings the option to specify the defaulting directory/s for the generated Windows environment/s. To iterate, the "Music, Videos, Downloads, ..." within the Wine Configuration point to /home/$USER/.var/app/com.usebottles.bottles which apparently create these directories in /home/$USER/Documents/{Documents, Downloads, Videos...}

![Bottles-GitHub-Screenshot_20210724_183323-send](https://user-images.githubusercontent.com/3128819/126873929-d617bdae-e75c-425f-914e-231814526a45.png)

I have installed Bottles using flatpak on Fedora 34 KDE Plasma Workstation.

Is it possible to specify a location for this, for example, like in Lutris where there is an option to specify a working directory (example: /home/$USER/Games) or better yet (example: /home/$USER/Bottles/{Env1-Games, Env2-Software})/.

P.S. 
Even an "ENV0-Sharing" where common files can exist and be hard-linked to each env that uses them - this is an extra, for btrfs file systems, I don't think that will matter so much.

P.P.S. If I have not seen an existing solution to the problem, please, point it out and we can delete the issue. 

Thank you in advance. Have a good day.

**Comment by mirkobrombin** [comment]
Hi! Thanks a lot for the kind words.
I have never thought about this feature but it is actually very important and I want to integrate it as soon as possible.

I need to understand how Lutris (and others?) Handle this. I need to figure out if the change is not a problem with the current codebase otherwise I have to schedule in the fourth version where we have a better integration with Wine. Thanks again to take this to my attention!

**Comment by mirkobrombin** [comment]
From what I can see, Lutris uses the current working directory (cwd) to set the path to work in. It's funny because without knowing it we already do it in Bottles 4:
- https://github.com/bottlesdevs/LibraryWine/blob/23c9e32e58bbc994aafbdee061058a7403b83711/Bottles.LibraryWine/Wine.cs#L115
- https://github.com/bottlesdevs/libwine/blob/98a3cd50960f013341b83c8b8541903304115034/libwine/utils/command.py#L13

**Comment by mirkobrombin** [comment]
Just implemented
