### ISSUE TITLE
[Bug] - Error when using special characters in Bottles v1

### ISSUE THREAD

**Issue by erazemk** [bottlesdevs/Bottles#40]
Your hint (*Microsoft Office*) implies that the user can name the prefix whatever they want including having spaces, which doesn't work.

Here's the relevant error message:
```python
Error: [BOTTLE_NAME_ERROR] Bottle name can not contain special characters
Traceback (most recent call last):
  File "/usr/share/com.github.mirkobrombin.bottles/bottles/headerbar.py", line 125, in on_save_clicked
    self.wine.create_bottle(name, arch)
  File "/usr/share/com.github.mirkobrombin.bottles/bottles/wine.py", line 274, in create_bottle
    if self.check_special_chars(name):
  File "/usr/share/com.github.mirkobrombin.bottles/bottles/wine.py", line 259, in check_special_chars
    message_dialog = Gtk.MessageDialog.new_with_image_from_icon_name(
AttributeError: type object 'MessageDialog' has no attribute 'new_with_image_from_icon_name'
```

In my opinion the most user friendly way (maybe not the simplest) would be to add an error message if the name contains special characters.

**Comment by mirkobrombin** [comment]
The application (should) already popup a message for this. 

https://github.com/mirkobrombin/Bottles/blob/4e34404060f0e7ca615ee1700fda7d178b90a49d/bottles/wine.py#L259

An update must have broken something because the attrivute `new_with_image_from_icon_name` cannot be found anymore for `MessageDialog` object.

I will check for a solution, thanks for feedback.

**Comment by mirkobrombin** [comment]
Fixed in V1.
