### ISSUE TITLE
[Request] Change default bottle path

### ISSUE THREAD

**Issue by ktzee** [bottlesdevs/Bottles#578]
**Is your feature request related to a problem? Please describe.**
I have a ~/Games path, which is where I keep my Lutris prefixes and my Steam library. When I import a prefix into Bottles, though, the default path is ~/.local/share/bottles/bottles/. I'd like a way to specify the default path for Bottle's prefixes. 

**Describe the solution you'd like**
A "Bottle Default Path" configuration option.

**Describe alternatives you've considered**
The only workaround I could think of, so far, is to manually move the prefix, and then change the "working directory" option within the Bottle's bottle.

**Additional context**
I actually have a different disk mounted on ~/Games, to avoid my home to be filled by games. Having Bottles use ~/.local/share/ means my home gets full.

**Comment by ktzee** [comment]
Note: the workaround I mentioned doesn't actually work. In the bottle's Preferences, the "Working directory" item only opens a file manager pointed to the bottle's path.

**Comment by mirkobrombin** [comment]
The working directory (cwd, current working directory) is used by the runner to determinate the path where the process will be spawned, so the executable can find its files. It is not intended for that purpose. 

Currently Bottles has a "complex" structure because it is served in different ways (flatpak and snap use the sandboxed path and other use the .local path). With Bottles v2 we wanted to allow the use of custom paths but the functionality has never been implemented. It will certainly be implemented in the future, allowing the user to change the default path from the software preferences. Unfortunately, at the moment I don't have enough time to devote to such a feature.

A possible workaround could be to create a symbolic link of the path bottles to another location you prefer. Keep in mind, however, that Bottles prefixes are not common and it is important to act on them through the Bottles interface or console, so that it can read and apply the bottle configuration.

**Comment by TibixDev** [comment]
I'd be happy if this feature was added too.

**Comment by EvoXCX** [comment]
+1

**Comment by NGStaph** [comment]
How can i use this functionality?
