### ISSUE TITLE
[Request] Add Wine state indicator

### ISSUE THREAD

**Issue by ACertainTopfi** [bottlesdevs/Bottles#635]
**Is your feature request related to a problem? Please describe.**
Currently, there is no indicator that shows the state a Wine process is in. This makes it frustrating as one can not tell whether the process has actually been started or shutdown/killed.

**Describe the solution you'd like**
A simple indicator in line with the controls that shows the state via a simple unicode symbol. Example pictures below.

**Describe alternatives you've considered**
Currently launching bottles via the terminal so I have feedback over the process state and can be sure it has fully started/stopped.

**Additional context**
![Bildschirmfoto von 2021-10-17 03-15-311](https://user-images.githubusercontent.com/79299376/137606540-dbc826e0-a9d5-4a6f-baec-1234b830f0b9.png)
![Bildschirmfoto von 2021-10-17 03-15-31](https://user-images.githubusercontent.com/79299376/137606544-b5e20115-ed29-4925-bf38-23f333eea3f3.png)

**Comment by mirkobrombin** [comment]
To understand if it is running, we should have access to the processes running in the bottle. In libwine we have already implemented this thing and it shouldn't be too difficult to implement it in Bottles. 

I would create a queue where to insert all the processes started via utility, program list or manually by the user and I would check every X which processes are still alive. So in the UI I would implement it differently, for example a menubutton with a popover showing the running processes.

**Comment by mirkobrombin** [comment]
Now there is a [per-bottle Task Manager](https://usebottles.com/blog/release-2021.11.28/#new-task-manager), where users can see if there are running processes. I think this is a better way, because showing an icon when there are processes running in the bottle may not be enough and give false positives. This is because the running processes could be "system" (by WINE), so if the executable launched by the user is crashed, the icon will still show that there are some processes running, without giving the actual feedback for the user's executable.

Feel free to add more details!
