### ISSUE TITLE
[Request] Optional close Bottles when a program is launched

### ISSUE THREAD

**Issue by WineBottles** [bottlesdevs/Bottles#701]
Is it possible for a setting to be added where once a program is launched then Bottles closes itself?

For example, I launch bottles. Click the play button beside my Wine game it launches in windowed mode and Bottles is still in the background. At this point Bottles does not need to be opened as it already did it's thing. When I close the game, I personally do not need to see Bottles again as I am done.

I understand others might, which is why it  could be a setting or maybe a per-program setting like "close Bottles when this program is launched"

I am using Flatpak version 2021.10.28-treviso

**Comment by mirkobrombin** [comment]
I think this function can be confused with the one we already have in the preferences but that only works if you start an executable from the file manager. 

I also believe that it is certainly useful to have it but that it is still an unnatural process. Would you close Steam once a game is started? A better solution would be to automatically close Bottles when starting a program via the system applications menu (we are working on the function that allows you to create desktop entries).

**Comment by Githob2021** [comment]
> I think this function can be confused with the one we already have in the preferences but that only works if you start an executable from the file manager.
> 
> I also believe that it is certainly useful to have it but that it is still an unnatural process. Would you close Steam once a game is started? A better solution would be to automatically close Bottles when starting a program via the system applications menu (we are working on the function that allows you to create desktop entries).

In my case I am not using Steam but launching a game from a games own launcher (Guild Wars 2) in this case. So once I would click play and the launcher is up there is no need for Bottles to be open in the background. It's kind of like launchception. Bottles -> GW2 launcher -> Guild Wars 2. The GW2 Launcher closes itself once it launches the game, but Bottles stays open.

**Comment by mirkobrombin** [comment]
> > I think this function can be confused with the one we already have in the preferences but that only works if you start an executable from the file manager.
> > I also believe that it is certainly useful to have it but that it is still an unnatural process. Would you close Steam once a game is started? A better solution would be to automatically close Bottles when starting a program via the system applications menu (we are working on the function that allows you to create desktop entries).
> 
> In my case I am not using Steam but launching a game from a games own launcher (Guild Wars 2) in this case. So once I would click play and the launcher is up there is no need for Bottles to be open in the background. It's kind of like launchception. Bottles -> GW2 launcher -> Guild Wars 2. The GW2 Launcher closes itself once it launches the game, but Bottles stays open.

I agree with you but I need to understand where and how to implement it. It shouldn't be a Bottles setting because it would affect all bottles and if you are experimenting with some configuration you have to turn it off and then go back to the bottle. In the same way I don't think it is correct to integrate it in the single bottle because the preferences are related to the prefix and not to how Bottles (the software) works.

If the intent is not to see Bottles (because it is not needed at that moment), the best hypothesis would be not to open it at all. For this I am talking about implementing the Desktop Entries, so from the program menu (in Bottles) you can generate the desktop entry and when you want to start the program you do it directly from the system menu, without showing Bottles at all.

**Comment by Githob2021** [comment]
> If the intent is not to see Bottles (because it is not needed at that moment), the best hypothesis would be not to open it at all. For this I am talking about implementing the Desktop Entries, so from the program menu (in Bottles) you can generate the desktop entry and when you want to start the program you do it directly from the system menu, without showing Bottles at all.

If I am understanding this correctly, that would be AMAZING. So basically I would pin Guild Wars 2 to my task manager at the bottom in KDE Plasma then just click the icon to launch it? And Bottles does everything in the background?

I updated the flatpak to latest version today (2021.11.14-treviso-1) and I do see a setting in preferences called "Close Bottles after starting a program" and I have it checked on but it doesn't seem to do anything. Whether it's in the on or off state nothing different is happening.

I may also need to put in a new bug ticket because I tried "Enable DLSS (DXVK-NVAPI) and when I close Bottles and reopen it, there is always a crash report:

[Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/nvapi//x32/nvapi.dll'  File "/app/share/bottles/bottles/utils.py", line 317, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/manager.py", line 1396, in install_nvapi
    shutil.copy(f"{nvapi_path}/{dll}/{dll_file}", inst_path)

  File "/usr/lib/python3.9/shutil.py", line 426, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "/usr/lib/python3.9/shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:

Anyway, thank you so much for your hard work! Bottles is so cool.

**Comment by mirkobrombin** [comment]
> > If the intent is not to see Bottles (because it is not needed at that moment), the best hypothesis would be not to open it at all. For this I am talking about implementing the Desktop Entries, so from the program menu (in Bottles) you can generate the desktop entry and when you want to start the program you do it directly from the system menu, without showing Bottles at all.
> 
> If I am understanding this correctly, that would be AMAZING. So basically I would pin Guild Wars 2 to my task manager at the bottom in KDE Plasma then just click the icon to launch it? And Bottles does everything in the background?
> 
> I updated the flatpak to latest version today (2021.11.14-treviso-1) and I do see a setting in preferences called "Close Bottles after starting a program" and I have it checked on but it doesn't seem to do anything. Whether it's in the on or off state nothing different is happening.
> 

That function is only for executables started by the file manager (it should be written).


> I may also need to put in a new bug ticket because I tried "Enable DLSS (DXVK-NVAPI) and when I close Bottles and reopen it, there is always a crash report:
> 
> [Errno 2] No such file or directory: '/home/USER/.var/app/com.usebottles.bottles/data/bottles/nvapi//x32/nvapi.dll' File "/app/share/bottles/bottles/utils.py", line 317, in __target result = self.task_func(*args, **kwargs)
> 
> File "/app/share/bottles/bottles/backend/manager.py", line 1396, in install_nvapi shutil.copy(f"{nvapi_path}/{dll}/{dll_file}", inst_path)
> 
> File "/usr/lib/python3.9/shutil.py", line 426, in copy copyfile(src, dst, follow_symlinks=follow_symlinks)
> 
> File "/usr/lib/python3.9/shutil.py", line 265, in copyfile with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> 

Yeh, bug! Please open a new issue for this 😁

> Anyway, thank you so much for your hard work! Bottles is so cool.

Thanks 😊

**Comment by mirkobrombin** [comment]
Closing as it is a wrong-by-default concept. To launch programs and closing Bottles, just make a desktop entry using the CLI. Desktop entries generator is coming to Flatpak too.
