### ISSUE TITLE
[Request] Adobe on Linux (creative cloud)

### ISSUE THREAD

**Issue by gregpalaci** [bottlesdevs/Bottles#717]
**Is your feature request related to a problem? Please describe.**
Thousands of frontend developers have been somewhat forced to use macOS historically if their workplace requires Photoshop, If bottles could support Creative Cloud it would really be a big deal in the community,

**Describe the solution you'd like**
An install of course... I guess a full "Design" environment

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.
](https://github.com/corbindavenport/creative-cloud-linux) It looks like there was work in this area but they hit a wall, I think bottles dependencies manager is probably what was missing? I don't 100% understand the issue, I think the author was referencing a native windows webview or something thats missing?

ere.

**Comment by mirkobrombin** [comment]
Mh interesting, I'll definitely try as soon as I have free time. Could you please move the issue to the programs repository?

**Comment by gregpalaci** [comment]
thanks so much, if you get a chance!

**Comment by Manibutt5286** [comment]
Hi Mirko,

as windows 11 now running ubuntu and cali linux.
with all native linux software.

can this be possible linux to make new Kernel with extra shell of windows supporter software.
i mean linux kernel core is dealing with hardware, then main OS GUI is coming in shell.

Is it possible to make Little New kernel in midlle of core and shell OS for the support of windows software.
which can can execute and run windows all program simply.

Middle kernel only deals with windows software dependencies and libraries (just like the same ), and whole Processed data which is Processed by middle kernel will delivery to Core linux kernel for Showing on screen through Graphic devices and Sound devices, i mean ouput. because we have Linux drivers.

yes this will take much space on hard disk, as well RAM will be loaded much more.
but can it be possible to run that kernel only when windows software we want to run on linux.
for this our Home / or root directory can have C: directory which have all  its components of program files, windows etc.

i know its the difficult task to make whole new kernel , its like whole new OS.
but this would be revolutionary.

thanks for you time dear.
waiting for your reply

Take care
