### ISSUE TITLE
[Request] Customizable entries for programs

### ISSUE THREAD

**Issue by eaglesemanation** [bottlesdevs/Bottles#750]
**Is your feature request related to a problem? Please describe.**
Possibly linked to #728. The issue is that I have a program that doesn't have an installer and no .lnk file is being generated. Because of that, I manually add .exe, but there are 2 problems with resulting entry:
1. There is no way of changing entry name without changing .exe file name, and I would prefer not to do that in case some mad developer decided to hardcode name of their binary.
2. Icon doesn't seem to be extracted from .exe. I'm not sure if it supposed to do that, but based on screenshots from documentation I assumed it should.

**Describe the solution you'd like**
I would love to see an option to change both name and icon of an entry, similarly to a name of a bottle.

**Describe alternatives you've considered**
An integrated tool for creating .lnk files, but I don't think it's a good idea.

**Comment by mirkobrombin** [comment]
Currently icons are not working due to backend changes and the sandbox. Reimplementing the feature can take long time because the new approach should be extracting it from the binary/lnk or looking for it in the drive (a long search process). 


Regarding the rename instead I think it is a good request and will be implemented.
