### ISSUE TITLE
Software doesn't explain what a bottle is

### ISSUE THREAD

**Issue by hadess** [bottlesdevs/Bottles#88]
It seems that the software expects us to already know what a "bottle" is. “It's a container for a Wine runner”. What's a Wine runner? What's Wine? :)

Some cues for vocabulary to be used could be taken from Boxes, which is a Virtual Machine manager, and has many of the same potential problems when it comes to technical vocabulary usage.

**Comment by mirkobrombin** [comment]
We are creating documentation for this, we must understand bring it to the UI.

I bring it to the attention of designers.

**Comment by hadess** [comment]
This isn't a question, FWIW, I already what those are. Somebody running the software for the first time might not.

I think that an empty state placeholder:
https://github.com/bottlesdevs/Bottles/issues/86
would be the right place to at least start defining some of those terms. Or maybe using "bottle" is something that should be left to the internals, and more common "container"/"virtual machine" vocabulary should be used instead in the UI.

**Comment by alvarlagerlof** [comment]
Hi @hadess 

We are aware that there are numerous issue with the app in its current form, in terms of how to use it and explaining what various concepts are about. We are however in the middle of a full redesign of the app that aims to make it easier to use and explain complex concepts to the user. We will be sure to look at what boxes does (I like the app a lot) and try to incorporate lessons learned from that here. 

If you're curious about the redesign, feel free to pop in on the link below and maybe make some comments. 

https://www.figma.com/file/2o1rKcFToABvzJFcxyy2v3/Bottles-Refresh?node-id=173%3A1348

**Comment by mirkobrombin** [comment]
It is about to be fixed in v3 with the new Onboard. This explains the basics and guides you through installing your first runner.

![Screenshot from 2021-01-24 17-48-23](https://user-images.githubusercontent.com/9479903/105637173-617d1b80-5e6c-11eb-869f-14795228513c.png)
![Screenshot from 2021-01-24 17-48-15](https://user-images.githubusercontent.com/9479903/105637175-6215b200-5e6c-11eb-9acf-f3098f1491d6.png)
![Screenshot from 2021-01-24 17-48-13](https://user-images.githubusercontent.com/9479903/105637176-6215b200-5e6c-11eb-9403-05a0e560d43a.png)
![Screenshot from 2021-01-24 17-48-12](https://user-images.githubusercontent.com/9479903/105637178-62ae4880-5e6c-11eb-932b-cce178969593.png)
![Screenshot from 2021-01-24 17-48-10](https://user-images.githubusercontent.com/9479903/105637180-62ae4880-5e6c-11eb-9546-3e70ac87399d.png)

Onboard replaces the old runner installation dialog (obviously). This can certainly be improved but it is a starting point. 

I keep this issue as a reference for the Onboard, for any tips and updates.

**Comment by alvarlagerlof** [comment]
Could possibly use a little more margin between the title and the text

**Comment by mirkobrombin** [comment]
> Could possibly use a little more margin between the title and the text. Otherwise very good

Yes, I try as soon as possible

**Comment by mirkobrombin** [comment]
Bottles v3 released. Have fun bug hunters!
