### ISSUE TITLE
[BUG] Special characters are available for bottle names - they are created without a name.

### ISSUE THREAD

**Issue by CleoMenezes** [bottlesdevs/Bottles#973]
**Describe the bug**
At bottle creation time, after writing any special character, it enables bottle creation.
In my case, I just put a space and it was discarded after creation and gives me the option to write the name of the bottle inside the bottle.
![image](https://user-images.githubusercontent.com/54215258/151257950-ce806157-f97e-4b3a-a2a1-c1b737679bfe.png)

**Installation**
 - Method: Flatpak
 - Version: 2022.1.14-trento-4

**To Reproduce**

https://user-images.githubusercontent.com/54215258/151257527-6e469a8d-f29c-4de1-855e-cd275b883037.mp4

**Expected behavior**
A warning message that only one character or special characters are not allowed.

**Screenshots**
![image](https://user-images.githubusercontent.com/54215258/151257677-89a667ef-8496-4aa2-a5b2-8a126cf28011.png)

**Desktop (please complete the following information):**
 - OS: Fedora Workstation
 - Version: 35
 - Display server: Wayland

**Comment by Githob2021** [comment]
There needs to be more safeties put in place for file names (like more than 1 char min and cannot start with space). But I have multiple bottles that have a spaces and special characters (dashes) inside the name.

For example "Gears of War" which then looks like this on your file explorer: "Gears-of-War".

You can also do dashes like I have: "Fable - The Lost Chapters" which then looks like this in your file explorer: "Fable---The-Lost-Chapters".

Bottles seems to know if it's multiple dashes in a row that the second one is in the file name or something a long those lines (pun, lol).

I guess Bottles cannot create a starting with a space bottle because then it would be broken in your file explorer. However, in that case as you mentioned, there should be a safety in place that stops the user. Same with the 2 characters minimum.
